linuxdeepin/dde-cooperation

.gitignore
src/dde-cooperation/meson.build

The meson build opened by qtcreater, but it can not open the resource file, because it can not find this resource path.
Log: Fix can not open resource in qtcreator

chore: Fix can not open resource in qtcreator

---

.gitmodules
debian/changelog

The submodule sources will be excluded which has been defined in the .gitmodules, this block CRP build that is in internal network.
Log: remove submodules define.

fix: Remove submodules

---

3rdparty/coost/src/CMakeLists.txt
3rdparty/coost/src/co/context/arch.h
3rdparty/coost/src/co/context/context.cc
3rdparty/coost/src/co/io_event.cc
3rdparty/coost/src/co/sock.cc
3rdparty/coost/src/so/ssl.cc
3rdparty/coost/src/so/tcp.cc
3rdparty/zrpc/src/net/tcpconnection.cpp
src/common/constant.h
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h
src/plugins/daemon/core/service/session.cpp
src/plugins/daemon/core/service/session.h
src/plugins/daemon/core/service/transferjob.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h

On some HW platform, it does not support context swap for coroutine, use thread instead go.
Log: detach coroutine.

chore: Detach coroutine for unsupported platform.

---

src/plugins/daemon/core/service/session.cpp

The thread lamada function crash on win, use go/wg replace it.
Log: fix crash on win.

fix: Fix thread crash on win

---

3rdparty/coost/src/co/context/arch.h
3rdparty/coost/src/co/context/context.S
3rdparty/coost/src/co/context/context.cc
3rdparty/coost/src/co/io_event.cc
3rdparty/coost/src/co/sock.cc
3rdparty/coost/src/so/ssl.cc
3rdparty/coost/src/so/tcp.cc
CMakeLists.txt
src/common/constant.h

Because of the coost coroutine 'go' is unstable, the thread detach instead of it.
Log: Disable coroutine.

chore: Disable coroutine

---

3rdparty/coost/src/so/rpc.cc
3rdparty/coost/src/so/tcp.cc
src/apps/data-transfer/main.cpp
src/plugins/data-transfer/core/gui/connect/custommessagebox.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h

If the process uses socket on windows, then this process can not exit normally even has closed socket. Force abort at end in order to workaround this issue.
Log: fix exit bug.

Fix: [win] fix process can not exit

---

src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp

After the delivery between two devices is completed, then a third device is used to deliver the file to the receiving device, and the receiving device does not respond
Log: After the delivery between two devices is completed, then a third device is used to deliver the file to the receiving device, and the receiving device does not respond
Bug: https://pms.uniontech.com/bug-view-228459.html

fix: 两个设备之间的投送完成后，再用第三个设备投送文件到接收设备，接收设备无响应

---

3rdparty/coost/src/so/rpc.cc
3rdparty/coost/src/so/tcp.cc
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h

Modify the back-end discovery logic to only send signals for every time there is a change
Log: Modify the back-end discovery logic to only send signals for every time there is a change

fix: Modify the back-end discovery logic to only send signals for every time there is a change

---

src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/utils/config.h

Added to cache to read file configuration, not cached during setup
Log: File Delivery - Invalid file save location setting
Bug: https://pms.uniontech.com/bug-view-232831.html

fix: File Delivery - Invalid file save location setting

---

3rdparty/zrpc/include/zrpc.h
3rdparty/zrpc/src/net/tcpbuffer.cpp
3rdparty/zrpc/src/net/tcpclient.cpp
3rdparty/zrpc/src/net/tcpconnection.cpp
3rdparty/zrpc/src/net/tcpconnection.h
3rdparty/zrpc/src/net/tcpserver.cpp
3rdparty/zrpc/src/net/tcpserver.h
3rdparty/zrpc/src/spec/rpcchannel.cpp
3rdparty/zrpc/src/zrpc.cpp
src/plugins/daemon/core/service/comshare.cpp
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h

Change to a short connection, send once and close TCP once. Modifying the issue of sending data errors
Log: Unable to transfer files again after network disconnection

fix: Unable to transfer files again after network disconnection

---

src/plugins/daemon/core/service/servicemanager.cpp

Donot need to start daemon, the service will auto launch it.
Log: fix bug.

fix: Donot need to start daemon

---

src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.h
src/plugins/cooperation/core/utils/cooperationutil.cpp

Symptom After the remote device is disconnected and reconnected, the device status is displayed incorrectly
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-234325.html

fix: The device status is displayed incorrectly

---

src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/data-transfer/core/utils/transferworker.cpp

It should cancel running transfer job if the frontend exit by user.
Log: Fix cancel issue.

fix: Cancel job if frontend exit

---

src/plugins/data-transfer/core/utils/transferworker.cpp

If the user cancel accept, the sender(win) not break.
Log: Fix cancel UI not change.

fix: Fix sender no change UI if remote cancel

---

src/common/commonstruct.h
src/common/commonstruct.proto
src/ipc/bridge.h
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h

Add/Cancel Sharing Connection Agreement
Log: After initiating a collaboration application, clicking the cancel button is invalid
Bug: https://pms.uniontech.com/bug-view-232941.html

fix: After initiating a collaboration application, clicking the cancel button is invalid

---

src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/daemon/utils/cooperationutil.cpp
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/ipc/sendipcservice.cpp
src/plugins/daemon/core/service/ipc/sendipcservice.h
src/plugins/daemon/core/service/searchlight.cpp

Upon receiving the offline message, disconnect the current connection and notify the offline user again
Log: The UOS end still displays a collaborative state with Win
Bug: https://pms.uniontech.com/bug-view-233775.html

fix: The UOS end still displays a collaborative state with Win

---

src/plugins/cooperation/core/proxy/cooperationproxy.cpp

Handle receiving server launch, register yourself, other devices can only discover it
Log: Handle receiving server launch, register yourself, other devices can only discover it

fix: Handle receiving server launch, register yourself, other devices can only discover it

---

src/common/commonstruct.h
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/service/jobmanager.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

Add disk space check and prompts
Log: The receiving party has insufficient storage space and does not receive a prompt indicating insufficient space. Reception failed
Bug: https://pms.uniontech.com/bug-view-228367.html https://pms.uniontech.com/bug-view-234177.html

fix: The receiving party has insufficient storage space and does not receive a prompt indicating insufficient space. Reception failed

---

src/common/constant.h
src/ipc/proto/chan.h
src/ipc/proto/chan.proto
src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationmanager.h
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.h
src/plugins/cooperation/daemon/utils/cooperationutil.cpp
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/sendipcservice.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlesendresultservice.cpp

Add network disconnection prompt
Log: There is no prompt when the receiver and sender networks are disconnected
Bug: https://pms.uniontech.com/bug-view-228107.html

fix: There is no prompt when the receiver and sender networks are disconnected

---

src/plugins/daemon/core/service/ipc/sendipcservice.cpp
src/plugins/daemon/core/service/job/transferjob.cpp

Network disconnection prompt indicates that it has been written backwards
Log: Network disconnection prompt indicates that it has been written backwards

fix: Network disconnection prompt indicates that it has been written backwards

---

src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/service/jobmanager.cpp

Incomplete processing of exiting file task
Log: When transferring files, the network is disconnected, and the second file delivery will immediately prompt a failure message
Bug: https://pms.uniontech.com/bug-view-239299.html

fix: When transferring files, the network is disconnected, and the second file delivery will immediately prompt a failure message

---

src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/daemon/core/service/ipc/sendipcservice.cpp

Add self drawn background and prompt box
Log: Win, settings - name missing error prompt
Bug: https://pms.uniontech.com/bug-view-238419.html

fix: Win, settings - name missing error prompt

---

src/plugins/cooperation/core/gui/widgets/filechooseredit.cpp
src/plugins/cooperation/core/gui/widgets/filechooseredit.h

Modified qlabel to dlineedit control
Log: In dark mode, the input box for saving files in the settings is not adapted to dark mode
Bug: https://pms.uniontech.com/bug-view-238233.html

fix: In dark mode, the input box for saving files in the settings is not adapted to dark mode

---

src/plugins/cooperation/core/gui/dialogs/transferdialog.cpp

The gap between the pop-up window and the title is too large during file delivery
Log: The gap between the pop-up window and the title is too large during file delivery
Bug: https://pms.uniontech.com/bug-view-238225.html

fix: The gap between the pop-up window and the title is too large during file delivery

---

.github/workflows/windows-mingw.yml

Fix win CI build do not work, it does not work normally if build with 5.15.2, fix build with Qt5.14.2 on windows-2019.
Log: Fix win CI build do not work.

fix: Fix win CI build do not work

---

src/plugins/cooperation/core/gui/widgets/filechooseredit.cpp
src/plugins/cooperation/core/gui/widgets/filechooseredit.h

Using dlineedit on Linux
Log: The input box for the file save location is not adapted to dark mode
Bug: https://pms.uniontech.com/bug-view-238233.html

fix: The input box for the file save location is not adapted to dark mode

---

src/plugins/cooperation/core/cooperation/cooperationtaskdialog.cpp
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.h
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/dialogs/transferdialog.cpp
src/plugins/cooperation/core/gui/dialogs/transferdialog.h
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.h
src/plugins/cooperation/core/gui/widgets/deviceitem.cpp
src/plugins/cooperation/core/gui/widgets/deviceitem.h
src/plugins/cooperation/core/gui/widgets/settingitem.cpp
src/plugins/cooperation/core/gui/win/cooperationsearchedit.h
src/plugins/cooperation/core/proxy/cooperationdialog.cpp
src/plugins/cooperation/core/proxy/cooperationdialog.h

Replace all qlabels with dlabels
Log: In compact mode, setting the text size is not compatible with compact mode
Bug: https://pms.uniontech.com/bug-view-238237.html

fix: In compact mode, setting the text size is not compatible with compact mode

---

src/plugins/cooperation/core/gui/widgets/deviceitem.cpp

In compact mode, the device list is not adapted to compact mode
Log: In compact mode, the device list is not adapted to compact mode
Bug: In compact mode, the device list is not adapted to compact mode

fix: In compact mode, the device list is not adapted to compact mode

---

src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp
src/plugins/daemon/core/service/job/transferjob.cpp

It may fail to free file fd on Win, and should notify frontend if there is any exception.
Log: Fix file IO error.
Bug: https://pms.uniontech.com/bug-view-243813.html

fix: Fix file IO error

---

cmake/version.cmake
src/apps/dde-cooperation/res/win/main.vbs

In order to free the backend file handle, kill it if the frontend app exit.
Log: exit backend after app quit.

Fix: the backend do not exit on win

---

src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp

It does not set the default value into json file, that cause setting not change, or sync to backend.
Log: fix first save dir invalid.
Bug: https://pms.uniontech.com/bug-view-243805.html

fix: storage dir config invalid at first time

---

.github/workflows/windows-mingw.yml

The win build env miss openssl,zlib, high cmake version can not find these libs. fixed version on 3.20.0.
Log: fix win ci build.

chore: Fix win build env

---

src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp

Some items of config uninit at first time, cause save setting invalid.
Log: fix first time config issue.

Fix: Do not init config for win

---

src/ipc/proto/chan.h
src/ipc/proto/chan.proto

The offset should be int64, but it static cast from uint32 * BLOCK_SIZE, which still max uint32 value.
Log: Fix max file size 4G issue.
Bug: https://pms.uniontech.com/bug-view-250159.html

fix: Fix max file size 4G issue

---

3rdparty/coost/src/co/context/arch.h

add riscv64 architecture support
Log:

feat: add riscv64 architecture support

---

src/plugins/daemon/core/service/ipc/sendipcservice.cpp

On some wifi network, the discovery may lost node and then stop all share.
Log: fix share disconnect issue.
Bug: no link.

fix: [share]Fix share may disconnect on WIFI

---

src/lib/cooperation/core/cooperation/cooperationmanager.cpp
src/lib/cooperation/core/discovercontroller/discovercontroller.cpp
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/maincontroller/win/maincontroller_win.cpp
src/lib/cooperation/core/transfer/transferhelper.cpp

It connects signal loop when self init, use app's activate window replace the main window, and the list abort when app exit.
Log: Fix runtime issue.

fix: Fix runtime issue

---

src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/common/manager/transferworker.cpp
src/lib/common/manager/transferworker.h
src/lib/common/session/protoserver.cpp
src/lib/common/session/protoserver.h

It can not send request again if remote restart, it can not get the remote address from the session when disconnected, and we need to reset all connected target.
Log: Fix communication freeze issue.

fix: Fix communication freeze issue

---

src/lib/common/manager/sessionworker.cpp
src/lib/common/session/protoclient.cpp
src/lib/common/session/protoclient.h
src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/discover/discovercontroller.h
src/lib/cooperation/core/gui/widgets/workspacewidget.cpp
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/networkutil.cpp

It uses async connect and do not get connect state immediately, use thread yield in order to avoid getting stuck. Enable search and update info into discovery.
Log: Fix async rpc and search.

fix: Fix async rpc and search

---

3rdparty/CppServer/source/server/http/http_request.cpp
src/apps/launcher/CMakeLists.txt
src/apps/launcher/main.cpp
src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/tokencache.cpp

The http parse incorrect request url if it includes space, it cause crash when verify error token.
Log: Fix http get error header.

fix: Fix http get error header

---

3rdparty/zrpc/src/net/tcpclient.cpp
src/common/constant.h
src/plugins/cooperation/daemon/utils/cooperationutil.cpp
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/jobmanager.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/servicemanager.cpp

libcoost creates persistent static resources for each thread, which can cause memory leaks when threads are frequently created and released using a thread pool to avoid frequent creation and destruction of threads Log: Fix memory leaks
Bug: https://pms.uniontech.com/bug-view-266935.html

fix: [memory leaks] Fix memory leaks

---

src/plugins/daemon/core/daemoncoreplugin.cpp

The default number of thread pools is too low, resulting in communication failure
Log: [thread] Increase the initial number of threads in threadpool
Bug: https://pms.uniontech.com/bug-view-273695.html

fix: [thread] Increase the initial number of threads in threadpool

---

src/lib/cooperation/core/utils/cooperationutil_p.h

When App start up, it publics first and the compated deamon is launched later, so it do not registor into daemon, that cause other old protocol can not discovery it.
Log: Fix disvovery issue after start up.
Bug: https://pms.uniontech.com/bug-view-273665.html

fix: Fix discovery issue

---

src/ipc/proto/comstruct.h
src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationmanager.h
src/plugins/cooperation/core/discover/discovercontroller.cpp
src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/gui/mainwindow.cpp
src/plugins/cooperation/core/gui/mainwindow.h
src/plugins/cooperation/core/gui/mainwindow_p.h
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/cooperationutil.h
src/plugins/daemon/core/service/discoveryjob.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_bo.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

Record the searched devices and provide the option to minimize pallets
Log: [optimization] Optimize user experience
Bug: https://pms.uniontech.com/bug-view-250143.html

fix: [optimization] Optimize user experience

---

src/lib/cooperation/core/net/helper/transferhelper.cpp
src/singleton/singleapplication.cpp

If the process crashed and then can not be launched. Use lock file to check.
Log: Fix can not be launched after crash.
Bug: https://pms.uniontech.com/bug-view-275523.html

fix: Fix single app issue

---

src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/net/compatwrapper.cpp
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/sharehelper.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/share/sharecooperationservice.cpp
src/lib/cooperation/core/share/sharecooperationservice.h

The shared target info is incorrect and do not check self sharing status that cause not update the share state if try to stop share.
Log: Fix share state not update.
Bug: https://pms.uniontech.com/bug-view-273413.html

fix: Fix share state issue

---

debian/changelog
src/configs/settings/settings.cpp

It uses the value as default value to compare, and then get no change if set value at first time.
Log: Fix config not change at first time.
Bug: https://pms.uniontech.com/bug-view-275517.html

fix: Fix config and new 0.9.2 tag

---

src/configs/settings/settings.cpp
src/plugins/cooperation/core/gui/dialogs/transferdialog.cpp
src/plugins/cooperation/core/gui/dialogs/transferdialog.h
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.h
src/plugins/cooperation/core/gui/widgets/firsttipwidget.cpp
src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/transfer/transferhelper_p.h

fix ui bug
Log: fix ui bug
Bug: https://pms.uniontech.com/bug-view-256019.html

fix: [ui] fix ui bug 108

---

src/plugins/data-transfer/core/gui/connect/connectwidget.cpp

fix the password for the connection page is not complete in tibetan
Log: fix the password display is incomplete
Bug: https://pms.uniontech.com/bug-view-250623.html

fix: [UI] fix the password display is incomplet

---

src/lib/cooperation/core/gui/phone/screenmirroringwindow.cpp
src/lib/cooperation/core/gui/phone/screenmirroringwindow.h

Record the expect size if not resized and then do size change after window change to normal.
Log: Fix the vnc view not change mode if mobile has changed show mode.
Bug: https://pms.uniontech.com/bug-view-283569.html

fix: Fix the vnc view not change mode if mobile has changed show mode

---

src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/sharehelper.h
src/lib/cooperation/core/net/helper/sharehelper_p.h
src/lib/cooperation/core/share/sharecooperationservice.cpp
src/lib/cooperation/core/share/sharecooperationservice.h
src/lib/cooperation/core/share/sharecooperationservicemanager.cpp

cherry-pick two changes from v25 dev

cherry-pick two changes from v25 dev

---

src/lib/cooperation/core/gui/dialogs/settingdialog.cpp
src/lib/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/lib/cooperation/core/gui/widgets/firsttipwidget.cpp
src/lib/cooperation/core/gui/widgets/firsttipwidget.h
src/lib/cooperation/core/share/sharecooperationservice.cpp
src/lib/cooperation/core/share/sharecooperationservice.h

Terminate all barrier process before start one in roder to make sure only one client or server is working.
Log: Terminate all process before start one。

fix: [share]Terminate all process before start one

---

debian/changelog

v1.0.2 release for demo on v20 and v25.
Log: v1.0.2 release for demo.

chore: [tag]v1.0.2 release for demo

---

src/lib/cooperation/core/net/helper/dialogs/cooperationdialog.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp

The transfer dialog can not be showed in parent's center that caused by without fixed width. Set fixed its height only once in order to workaround crash treeland and icon show not smooth issue.
Log: Fix the transfer dialog does not show in center.

fix: Fix the transfer dialog does not show in center

---

src/lib/cooperation/core/CMakeLists.txt
src/lib/cooperation/core/cooperationcoreplugin.cpp
src/lib/cooperation/core/cooperationcoreplugin.h
src/lib/cooperation/core/gui/linux/mainwindow_p_linux.cpp
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/gui/mainwindow.h
src/lib/cooperation/core/gui/mainwindow_p.h
src/lib/cooperation/core/gui/widgets/workspacewidget.cpp
src/lib/cooperation/core/gui/win/mainwindow_p_win.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/transfer/CMakeLists.txt

After the UI change which support mobile for UOS, it blocks windows building, remove phone classes from cooperation-transfer.
Log: Enable windows building after UI changed.

fix: [win]Enable windows building after UI changed

---

src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/discover/discovercontroller.h
src/lib/cooperation/core/gui/utils/sortfilterworker.cpp

It shoulds update status if in history or remove it. Set default status as connectable when parsing it.
Log: Fix incorrect status issue.
Bug: https://pms.uniontech.com/bug-view-289915.html

fix: Fix incorrect status issue

---

src/lib/cooperation/core/share/sharecooperationservice.cpp

If the main process exit by unkown reason, i.e crash or killed, the barrier process is running that cause cooperation did not stop. Kill them if process was recorded and app launchup in order to workaround this issue.
Log: Fix still control caused by barrier did not exit
Bug: https://pms.uniontech.com/bug-view-290819.html

fix: Fix still control caused by barrier did not exit

---

src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/linux/noticeutil.cpp
src/lib/cooperation/core/net/linux/noticeutil.h

After request has been canceled by remote target, reset the notify id, then ignore accept action.
Log: Fix it still continue cooperation even has been canceled.
Bug: https://pms.uniontech.com/bug-view-291005.html

fix: Fix it still continue cooperation even has been canceled

---

src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.h

On some OS version, it returns last id if not click the notification, reset the id in order to workaround it.
Log: Workaround notification incorrect issue.
Bug: https://pms.uniontech.com/bug-view-299345.html

fix: Workaround notification incorrect issue

---

android/library/droidvnc-ng/libvncserver/include/rfb/rfbclient.h
android/library/droidvnc-ng/libvncserver/src/libvncclient/rfbclient.c
src/lib/cooperation/core/gui/phone/vncrecvthread.cpp
src/lib/cooperation/core/gui/phone/vncrecvthread.h
src/lib/cooperation/core/gui/phone/vncviewer.cpp
src/lib/cooperation/core/gui/phone/vncviewer.h
src/lib/cooperation/core/gui/widgets/firsttipwidget.cpp

It did not set correct rgba for light style, that cause show dark on Qt6 env.
Log: Fix light style issue.

fix: Fix light style issue and display issue

---

debian/changelog
src/lib/cooperation/dfmplugin/CMakeLists.txt

Remove unused depending dfm modules which block CI build.
Log: Fix CI build and v1.0.9 release.

fix: Fix CI build and tag v1.0.9

---

src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper_p.h
src/lib/cooperation/core/net/linux/noticeutil.cpp
src/singleton/singleapplication.cpp

Set id as 0 in order to show new notification, otherwise it will show last notification again by id.
Log: Fix notification do not update issue.
Bug: https://pms.uniontech.com/bug-view-299345.html

fix: Fix notification do not update issue

---

src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/utils/cooperationutil.cpp
src/lib/cooperation/core/utils/cooperationutil.h

The dialog's parent is null, get from main windows and set into dialog.
Log: Fix dialog does not show in center.
Bug: https://pms.uniontech.com/bug-view-299545.html

fix: Fix dialog does not show in center

---

src/configs/settings/settings.cpp
src/lib/cooperation/dfmplugin/configs/settings/settings.cpp

The QVariant::Invalid is valid value 0 if set as default since Qt6, use QVariant() replace it.
Log: Fix incorrect default setting.
Bug: https://pms.uniontech.com/bug-view-303425.html

fix: Fix incorrect default setting

---

src/lib/cooperation/core/gui/mainwindow.cpp

Move the close dialog to parent's center.
Log: Fix close dialog not show in center.
Bug: https://pms.uniontech.com/bug-view-277885.html

fix: Fix close dialog not show in center

---

src/compat/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper_p.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/networkutil.h

After it works with the new version target, it can not handle the request from old version target.
Log: Fix work with compat target issue.
Bug: https://pms.uniontech.com/bug-view-303473.html

fix: Fix work with compat target issue
