.obs/workflows.yml
.reuse/dep5
LICENSES/CC0-1.0.txt

chore(CI): add OBS workflows

---

misc/org.deepin.dde.cooperation.desktop

CLoses linuxdeepin/developer-center#3913

chore: show desktop entry

---

debian/changelog

chore: bump version to 0.0.6

---

meson.build
src/dde-cooperation/Android/qml/NewDevice.qml
src/dde-cooperation/ConfirmDialog.cc
src/dde-cooperation/Machine/Machine.cc
src/dde-cooperation/ReconnectDialog.cc
src/dde-cooperation/main.cc
translations/dde-cooperation_en.ts
translations/dde-cooperation_zh_CN.ts
translations/dde-cooperation_zh_HK.ts
translations/dde-cooperation_zh_TW.ts

Fixes linuxdeepin/developer-center#3669

feat: add multilingual support

---

src/dde-cooperation/Machine/Machine.cc

Fixes linuxdeepin/developer-center#3703

fix: direction settings have not been updated

---

debian/changelog

* add multilingual support
* fix direction settings have not been updated

chore: bump version to 0.0.7

---

misc/org.deepin.dde.cooperation.desktop

linuxdeepin/developer-center#3806

chore: 修改桌面条目名

---

src/dde-cooperation/Android/qml/MainWindow.qml
src/dde-cooperation/Android/qml/NewDevice.qml

* 窗口自适应 Loader 大小
* 连接安卓设备页面 UI 修改
linuxdeepin/developer-center#3806

chore: 优化 UI

---

misc/org.deepin.dde.cooperation.desktop

Fixes: linuxdeepin/developer-center#4064

fix: dock icon display incorrectly.

---

debian/changelog

* fix dock icon display incorrectly
* optimize UI
* change the name of desktop entry

chore: bump version to 0.0.8

---

src/dde-cooperation/Android/AndroidMainWindow.cc
src/dde-cooperation/Android/AndroidMainWindow.h
src/dde-cooperation/Android/qml/MainWindow.qml
src/dde-cooperation/Machine/AndroidMachine.cc
src/dde-cooperation/Machine/AndroidMachine.h
src/dde-cooperation/Manager.cc
src/dde-cooperation/Manager.h

Issue: linuxdeepin/developer-center#4162

fix: window can't be reopened after closing

---

src/dde-cooperation/Android/qml/NewDevice.qml
translations/dde-cooperation_en.ts
translations/dde-cooperation_zh_CN.ts
translations/dde-cooperation_zh_HK.ts
translations/dde-cooperation_zh_TW.ts

Issue: linuxdeepin/developer-center#4162

chore: modify the wording

---

debian/changelog

* fix window can't be reopened after closing
* modify the wording

chore: bump version to 0.0.9

---

debian/changelog

chore: bump version to 0.0.10

---

debian/control
src/dde-cooperation/Machine/Machine.cc
src/dde-cooperation/Manager.cc
src/dde-cooperation/SendTransfer.cc
src/dde-cooperation/Wrappers/InputGrabbersManager.cc
src/dde-cooperation/X11/X11.cc
src/dde-cooperation/X11/X11.h
src/input-grabber/InputGrabber.cc
src/input-grabber/InputGrabber.h

fix a series of packaging dependency issues and qt version compatibility issues
Log: fix dependency configuration
Bug: no

fix: [build] fix dependency configuration

---

debian/changelog
debian/control
src/dde-cooperation/Android/qml/MainWindow.qml
src/dde-cooperation/Android/qml/NewDevice.qml
src/dde-cooperation/Android/qml/VideoPlayer.qml

reduce the version of QML from 5.15 to 5.11
Log: fix QML version dependency issue
Bug: no

fix: [qml] fix QML version dependency issue

---

CMakeLists.txt
src/apps/data-transfer/CMakeLists.txt
src/plugins/data-transfer/core/CMakeLists.txt
src/plugins/data-transfer/core/datatransfercoreplugin.cpp
src/plugins/data-transfer/core/datatransfercoreplugin.h
src/plugins/data-transfer/core/gui/linux/apptranswidget.cpp
src/plugins/data-transfer/core/gui/linux/apptranswidget.h
src/plugins/data-transfer/core/gui/linux/configtranswidget.cpp
src/plugins/data-transfer/core/gui/linux/configtranswidget.h
src/plugins/data-transfer/core/gui/linux/connectwidget.cpp
src/plugins/data-transfer/core/gui/linux/connectwidget.h
src/plugins/data-transfer/core/gui/linux/filetranswidget.cpp
src/plugins/data-transfer/core/gui/linux/filetranswidget.h
src/plugins/data-transfer/core/gui/linux/mainwindow.cpp
src/plugins/data-transfer/core/gui/linux/mainwindow.h
src/plugins/data-transfer/core/gui/linux/searchwidget.cpp
src/plugins/data-transfer/core/gui/linux/searchwidget.h
src/plugins/data-transfer/core/gui/linux/startwidget.cpp
src/plugins/data-transfer/core/gui/linux/startwidget.h
src/plugins/data-transfer/core/gui/linux/successwidget.cpp
src/plugins/data-transfer/core/gui/linux/successwidget.h
src/plugins/data-transfer/core/gui/linux/transferringwidget.cpp
src/plugins/data-transfer/core/gui/linux/transferringwidget.h
src/singleton/singleapplication.cpp
src/singleton/singleapplication.h

Added the initial version of UI
Log: init UI
Task: https://pms.uniontech.com/task-view-289729.html

feat: [UI] add linux ui

---

src/plugins/data-transfer/core/CMakeLists.txt
src/plugins/data-transfer/core/gui/linux/apptranswidget.cpp
src/plugins/data-transfer/core/gui/linux/apptranswidget.h
src/plugins/data-transfer/core/gui/linux/configtranswidget.cpp
src/plugins/data-transfer/core/gui/linux/configtranswidget.h
src/plugins/data-transfer/core/gui/linux/connectwidget.cpp
src/plugins/data-transfer/core/gui/linux/connectwidget.h
src/plugins/data-transfer/core/gui/linux/filetranswidget.cpp
src/plugins/data-transfer/core/gui/linux/filetranswidget.h
src/plugins/data-transfer/core/gui/linux/searchwidget.cpp
src/plugins/data-transfer/core/gui/linux/searchwidget.h
src/plugins/data-transfer/core/gui/linux/transferringwidget.cpp
src/plugins/data-transfer/core/utils/optionsmanager.cpp
src/plugins/data-transfer/core/utils/optionsmanager.h
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h

add some UI logical interactions
Log: add some UI logical interactions
Task: https://pms.uniontech.com/task-view-289729.html

feat: [ui] add ui logic

---

3rdparty/CMakeLists.txt
3rdparty/tinyrpc/.gitignore
3rdparty/tinyrpc/CMakeLists.txt
3rdparty/tinyrpc/README.md
3rdparty/tinyrpc/baseproto/CMakeLists.txt
3rdparty/tinyrpc/baseproto/rpc_service_ptl.proto
3rdparty/tinyrpc/include/tinyrpc/rpc_error_code.hpp
3rdparty/tinyrpc/include/tinyrpc/rpc_websocket_service.hpp
CMakeLists.txt
src/CMakeLists.txt
src/apps/CMakeLists.txt
src/apps/deamon/CMakeLists.txt
src/apps/deamon/main.cpp
src/common/ipcaction.h
src/common/ipcwraper.cpp
src/common/ipcwraper.h
src/common/rpcwraper.cpp
src/common/rpcwraper.h
src/plugins/CMakeLists.txt
src/plugins/cooperation/CMakeLists.txt
src/plugins/cooperation/core/CMakeLists.txt
src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/cooperationcoreplugin.h
src/plugins/cooperation/core/cooperationcoreplugin.json
src/protocol/CMakeLists.txt
src/protocol/message.proto

Add deamon app and RPC fw base on boost.
Log: add daemon fw.

feat: Add deamon fw

---

3rdparty/CMakeLists.txt
src/zrpc/include/netaddress.h
src/zrpc/include/rpcchannel.h
src/zrpc/include/rpccontroller.h
src/zrpc/include/zrpc.h
src/zrpc/sample/client.cpp
src/zrpc/sample/server.cpp
src/zrpc/src/net/netaddress.cpp
src/zrpc/src/net/tcpclient.cpp
src/zrpc/src/net/tcpclient.h
src/zrpc/src/net/tcpconnection.cpp
src/zrpc/src/net/tcpconnection.h
src/zrpc/src/net/tcpserver.cpp
src/zrpc/src/net/tcpserver.h
src/zrpc/src/spec/rpcchannel.cpp
src/zrpc/src/spec/rpccontroller.cpp
src/zrpc/src/zrpc.cpp

refactor the zrpc implement.
Log: refactor zrpc.

refactor: [zrpc] refactor

---

src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/connect/readywidget.h
src/plugins/data-transfer/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/configselectwidget.cpp
src/plugins/data-transfer/core/gui/select/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/select/createbackupfilewidget.h
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h

add windows ui
Log: add windows ui and data grabbing functions.

feat: [ui] add windows ui

---

3rdparty/zrpc/src/net/tcpconnection.cpp
3rdparty/zrpc/src/net/tcpconnection.h
src/apps/config.h.in
src/apps/daemon/main.cpp
src/plugins/daemon/core/CMakeLists.txt

fix uos compile
Log: fix uos compile

fix: [compile]fix uos compile

---

src/plugins/daemon/core/service/fsadapter.cpp
src/plugins/daemon/core/service/ipc/commonservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/utils/config.h
src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h
src/protocol/CMakeLists.txt

Polling to query connection status
Log: Polling to query connection status

feat: [ipc] add Polling to query connection status

---

3rdparty/zrpc/include/zrpc.h
3rdparty/zrpc/src/zrpc.cpp
src/plugins/daemon/core/CMakeLists.txt
src/plugins/daemon/core/service/ipc/commonservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/utils/config.h
src/plugins/daemon/core/utils/utils.h
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/transfer/successwidget.cpp
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

as title
Log: fix windows compile

fix: fix windows compile

---

src/apps/daemon/main.cpp
src/apps/data-transfer/main.cpp

as title.
Log: append plugin path for release version

fix: [plugin] plugin path for release

---

debian/changelog
debian/control

Add some dtk depending libraries.
Log: fix ci.

fix: Fix CI build

---

.gitmodules
debian/changelog

Reverts linuxdeepin/dde-cooperation#52

Revert "fix: Remove submodules"

---

src/plugins/data-transfer/core/CMakeLists.txt
src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/choosewidget.h
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/connect/startwidget.cpp
src/plugins/data-transfer/core/gui/icon/application-x-zip.svg
src/plugins/data-transfer/core/gui/icon/tab_close_normal.svg
src/plugins/data-transfer/core/gui/icon/warning.svg
src/plugins/data-transfer/core/gui/icon/warning2.svg
src/plugins/data-transfer/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/data-transfer/core/gui/mainwindow_p.h
src/plugins/data-transfer/core/gui/resources.qrc
src/plugins/data-transfer/core/gui/transfer/successwidget.cpp
src/plugins/data-transfer/core/gui/transfer/successwidget.h
src/plugins/data-transfer/core/gui/transfer/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/transfer/uploadfilewidget.h
src/plugins/data-transfer/core/gui/type_defines.h

Added import logic for backup files
Log: add backup upload

feat: [backup] add backup upload

---

3rdparty/zrpc/src/include/specodec.h
3rdparty/zrpc/src/spec/specodec.cpp

Fix win build fail issue.
Log: fix build.

fix: [build]Fix win build

---

src/ipc/backendservice.cpp
src/ipc/backendservice.h
src/ipc/frontendservice.cpp
src/ipc/frontendservice.h
src/ipc/proto/chan.h
src/ipc/proto/chan.proto
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h
src/plugins/daemon/core/service/transferjob.cpp
src/plugins/daemon/core/service/transferjob.h
src/plugins/daemon/core/utils/config.h
src/plugins/daemon/core/utils/utils.h
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h
src/protocol/message.proto

Implement file transfer status notification and fix save dir issue.
Log: notify file status.

feat: [trans]Implement file transfer status notification

---

src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/utils/cert.h

Load certs from temp bin file.
Log: Load bin certs.

feat: Load bin certs

---

src/ipc/frontendservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/transferjob.cpp
src/plugins/daemon/core/service/transferjob.h
src/plugins/data-transfer/core/utils/transferworker.cpp

Fix issue: the save dir s incorrect and notify file transfer status.
Log: fix bug.

fix: Fix file transfer issue

---

src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/icon/success half-96.svg
src/plugins/data-transfer/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/data-transfer/core/gui/resources.qrc
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.h
src/plugins/data-transfer/core/gui/transfer/waittransferwidget.cpp
src/plugins/data-transfer/core/gui/transfer/waittransferwidget.h
src/plugins/data-transfer/core/gui/type_defines.h
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h

Added some success pages
Log: Added some success pages

feat: [ui] Added some success pages

---

debian/control
src/CMakeLists.txt
src/common/constant.h
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h
src/plugins/daemon/core/service/transferjob.cpp
src/plugins/daemon/core/service/transferjob.h
src/plugins/data-transfer/core/utils/transferworker.cpp

Implement job status notification, include file transfer details.
Log: Implement job status notification.

feat: Implement job status notification

---

src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/connect/licensewidget.cpp
src/plugins/data-transfer/core/gui/connect/licensewidget.h
src/plugins/data-transfer/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/data-transfer/core/gui/transfer/errorwidget.cpp
src/plugins/data-transfer/core/gui/transfer/errorwidget.h
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.h
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h
src/plugins/data-transfer/core/utils/transferworker.cpp

Add handling file exception logic
Log: Add handling file exception logic

feat: [error] Add handling file exception logic

---

src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/transferjob.cpp
src/plugins/daemon/core/service/transferjob.h

Integrate all path as one job, and fix the save dir issue.
Log: Integrate transfer job.

feat: Integrate transfer job as one.

---

src/ipc/proto/chan.h
src/ipc/proto/chan.proto
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

Support login notify when after get login request.
Log: support ogin notify.

feat: Login notify

---

debian/changelog
src/apps/daemon/CMakeLists.txt
src/apps/daemon/main.cpp
src/plugins/daemon/core/CMakeLists.txt

Fix the daemon service can not auto start issue.
Log: fix bug.

fix: Fix daemon service auto start

---

src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/backupload/unzipwoker.h
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.h
src/plugins/data-transfer/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/data-transfer/core/gui/transfer/errorwidget.cpp
src/plugins/data-transfer/core/gui/transfer/errorwidget.h
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.h
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h

Add Out of Storage Handling
Log: Add Out of Storage Handling

feat: [error] Add Out of Storage Handling

---

src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.h
src/plugins/data-transfer/core/gui/getbackup/drapwindowsdata.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocesswidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.h
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/calculatefilesize.cpp
src/plugins/data-transfer/core/gui/select/calculatefilesize.h
src/plugins/data-transfer/core/gui/select/configselectwidget.cpp
src/plugins/data-transfer/core/gui/select/configselectwidget.h
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.h
src/plugins/data-transfer/core/gui/select/item.h
src/plugins/data-transfer/core/gui/select/selectmainwidget.cpp
src/plugins/data-transfer/core/gui/select/userselectfilesize.cpp
src/plugins/data-transfer/core/gui/select/userselectfilesize.h
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp

add calculate user directory size ,and add user-selectable file size ui
Log: add calculate user directory size ,and add user-selectable file size ui

feat: [ui]update select files size ui

---

src/common/constant.h
src/ipc/backendservice.cpp
src/ipc/backendservice.h
src/ipc/bridge.h
src/ipc/frontendservice.cpp
src/ipc/frontendservice.h
src/ipc/proto/backend.h
src/ipc/proto/backend.proto
src/ipc/proto/chan.h
src/ipc/proto/chan.proto
src/ipc/proto/comstruct.h
src/ipc/proto/comstruct.proto
src/ipc/proto/frontend.h
src/ipc/proto/frontend.proto
src/plugins/cooperation/transfer/utils/transferhelper.cpp
src/plugins/cooperation/transfer/utils/transferhelper.h
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h
src/plugins/daemon/core/service/session.cpp
src/plugins/daemon/core/service/session.h
src/plugins/daemon/core/service/transferjob.cpp
src/plugins/daemon/core/service/transferjob.h
src/plugins/daemon/core/utils/config.h
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h
src/protocol/message.pb.cc
src/protocol/message.pb.h
src/protocol/message.proto

Use channel replace the SIGNAL-SLOT, and union session for same frontend APP, add some customize config APIs.
Log: Reimplement IPC APIs.

refactor: Reimplement IPC APIs

---

src/plugins/data-transfer/core/CMakeLists.txt
src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/utils/settinghepler.cpp
src/plugins/data-transfer/core/utils/settinghepler.h
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h
src/plugins/data-transfer/core/utils/transferworker.cpp

Added logic for installing applications
Log: Added logic for installing applications

feat: [install app]Added logic for installing applications

---

debian/dde-cooperation.install
src/apps/daemon/CMakeLists.txt
src/apps/daemon/main.cpp
src/apps/daemon/service/cooperation-daemon.desktop
src/apps/daemon/service/cooperation-daemon.service
src/base/baseutils.cpp
src/base/baseutils.h
src/plugins/cooperation/transfer/transferplugin.cpp
src/plugins/daemon/core/daemoncoreplugin.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/utils/config.h
src/plugins/data-transfer/core/datatransfercoreplugin.cpp
src/singleton/singleapplication.cpp

Fix the default storage dir is '/', use user service instead of system. Define the log dir and enable count.
Log: fix bug.

fix: Fix default storage dir and define log dir

---

src/apps/data-transfer/CMakeLists.txt
src/apps/data-transfer/icons/icon.svg
src/apps/data-transfer/main.cpp
src/apps/data-transfer/resources.qrc
src/apps/data-transfer/singleapplication.cpp
src/apps/data-transfer/singleapplication.h
src/apps/data-transfer/type_defines.h
src/plugins/data-transfer/core/CMakeLists.txt
src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp

add dapplication for uos
Log: add dapplication for uos

feat: [dapplication] add dapplication for uos

---

src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.h
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.h
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.h
src/plugins/data-transfer/core/gui/select/calculatefilesize.cpp
src/plugins/data-transfer/core/gui/select/calculatefilesize.h
src/plugins/data-transfer/core/gui/select/configselectwidget.cpp
src/plugins/data-transfer/core/gui/select/configselectwidget.h
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.h
src/plugins/data-transfer/core/gui/select/selectmainwidget.cpp
src/plugins/data-transfer/core/gui/select/selectmainwidget.h
src/plugins/data-transfer/core/gui/transfer/successwidget.cpp
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/optionsmanager.cpp
src/plugins/data-transfer/core/utils/transferhepler.h

Fix the issue of backup file saving failing on drive C,Added a safe exit for backup file thread.
Log: Fix the issue of backup file saving failing on drive C,Added a safe exit for backup file thread.

fix: [zip] Fix backup file issue

---

src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/utils/settinghepler.cpp
src/plugins/data-transfer/core/utils/settinghepler.h
src/plugins/data-transfer/core/utils/transferhepler.cpp

fix dbus signal accept error，cause it was not initialized on the main thread
Log: fix dbus signal accept error

fix: [install app] dbus signal accept error

---

src/ipc/backendservice.cpp
src/ipc/backendservice.h
src/ipc/bridge.h
src/ipc/proto/backend.h
src/ipc/proto/backend.proto
src/ipc/proto/comstruct.h
src/ipc/proto/comstruct.proto
src/plugins/cooperation/transfer/utils/transferhelper.cpp
src/plugins/cooperation/transfer/utils/transferhelper.h
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/discoveryjob.h
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h

Enable app register or unregister its own node info.
Log: Enable app register node info

feat: Enable app register node info

---

src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/select/selectmainwidget.cpp
src/plugins/data-transfer/core/gui/select/selectmainwidget.h
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/settinghepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp

updated the selection icon for ChooseWidget
Log: updated the selection icon for ChooseWidget

feat: [ui] update choose widget

---

src/plugins/data-transfer/core/utils/settinghepler.cpp

changed bookmark name
Log: changed bookmark name

fix: [bookmarks] changed bookmark name

---

src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/discoveryjob.h
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h
src/plugins/daemon/core/service/servicemanager.cpp

Different threads manipulate the same resource
Log: Different threads manipulate the same resource

fix: dde-cooperate crash

---

debian/changelog

update changelog
Log:  update changelog

feat: [changelog] update changelog

---

src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h

Add to get all online apps
Log: Add to get all online apps

feat: Add to get all online apps

---

src/plugins/daemon/core/service/session.cpp

The socket connect request called by coroutine.
Log: fix bug.

fix: Fix crash by coroutine

---

src/apps/dde-cooperation-transfer/main.cpp
src/apps/dde-cooperation/main.cpp
src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/mainwindow.cpp
src/plugins/cooperation/core/gui/mainwindow.h
src/plugins/cooperation/core/gui/widgets/deviceitem.cpp
src/plugins/cooperation/core/gui/widgets/deviceitem.h
src/plugins/cooperation/core/gui/widgets/devicelistwidget.cpp
src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/gui/widgets/workspacewidget.h
src/plugins/cooperation/core/gui/widgets/workspacewidget_p.h
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/cooperationutil.h
src/plugins/cooperation/core/utils/cooperationutil_p.h
src/plugins/cooperation/core/utils/sortfilterworker.cpp
src/plugins/cooperation/core/utils/sortfilterworker.h
src/plugins/cooperation/transfer/transferplugin.cpp
src/plugins/cooperation/transfer/utils/transferhelper.cpp

as title
Log: code optimization
Task: https://pms.uniontech.com/task-view-296709.html

feat: code optimization for  device discovery

---

3rdparty/coost/src/co/context/arch.h
src/common/constant.h

Fix build on sw_64 platform.
Log: fix build.

fix: [build]Fix SW_64 build.

---

src/ipc/proto/backend.h
src/ipc/proto/backend.proto
src/ipc/proto/chan.h
src/ipc/proto/chan.proto
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h
src/plugins/daemon/core/service/transferjob.cpp
src/plugins/daemon/core/service/transferjob.h
src/protocol/message.pb.cc
src/protocol/message.pb.h
src/protocol/message.proto

modify cross-end file transfer request protocol
Log: modify cross-end file transfer request protocol

feat: modify cross-end file transfer request protocol

---

src/plugins/cooperation/transfer/global_defines.h
src/plugins/cooperation/transfer/transferplugin.cpp
src/plugins/cooperation/transfer/utils/transferhelper.cpp
src/plugins/cooperation/transfer/utils/transferhelper_p.h

as title
Log: file transfer
Task: https://pms.uniontech.com/task-view-296713.html

feat: File transfer for dde-cooperation

---

CMakeLists.txt
src/apps/dde-cooperation-transfer/CMakeLists.txt
src/apps/dde-cooperation-transfer/main.cpp
src/apps/dde-cooperation/CMakeLists.txt
src/apps/dde-cooperation/main.cpp
src/apps/dde-cooperation/resources/icons/deepin/builtin/icons/collaboration_32px.svg
src/apps/dde-cooperation/resources/resources.qrc
src/dde-cooperation-translate.sh
src/external/dde-file-manager-plugins/cooperation/cooperationplugin.cpp
src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/transfer/global_defines.h
src/plugins/cooperation/transfer/gui/transferdialog.cpp
src/plugins/cooperation/transfer/utils/transferhelper.cpp
src/plugins/cooperation/transfer/utils/transferhelper_p.h
src/plugins/daemon/core/service/servicemanager.cpp
src/singleton/singleapplication.cpp
src/singleton/singleapplication.h
src/translate_generation.sh
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

as title
Log: feature
Task: https://pms.uniontech.com/task-view-296713.html

feat: translation and file transfer

---

src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/job/communicationjob.cpp
src/plugins/daemon/core/service/job/communicationjob.h
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/protocol/message.pb.cc
src/protocol/message.pb.h
src/protocol/message.proto

Modify the back-end application transfer file protocol
Log: Modify the back-end application transfer file protocol

feat: Modify the back-end application transfer file protocol

---

debian/control
debian/dde-cooperation-daemon.install
debian/dde-cooperation-transfer.install
debian/dde-cooperation.install
src/CMakeLists.txt
src/apps/dde-cooperation/main.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/cooperationutil.h

fix: fix issue of discovery

---

src/plugins/daemon/core/service/job/communicationjob.cpp
src/plugins/daemon/core/service/job/communicationjob.h
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/session.cpp

Incorrect value returned when transferring a file
Log: Incorrect value returned when transferring a file

feat: Incorrect value returned when transferring a file

---

src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp

Debugging the file transfer backend code
Log: Debugging the file transfer backend code

feat: Debugging the file transfer backend code

---

3rdparty/coost/src/co/sched.cc
3rdparty/coost/src/so/rpc.cc
3rdparty/zrpc/src/net/tcpconnection.cpp
3rdparty/zrpc/src/net/tcpconnection.h

fix thread error
Log: fix thread error

fix: [thread] fix thread error

---

3rdparty/zrpc/include/rpcchannel.h
3rdparty/zrpc/src/spec/rpcchannel.cpp
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/job/communicationjob.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h

Adjustments to send to the front end can only be made by the main thread.
Log: Adjustments to send to the front end can only be made by the main thread.

feat: Adjustments to send to the front end can only be made by the main thread.

---

src/common/constant.h
src/external/dde-file-manager-plugins/cooperation/cooperationplugin.cpp
src/external/dde-file-manager-plugins/cooperation/menu/cooperationmenuscene.cpp
src/external/dde-file-manager-plugins/cooperation/menu/cooperationmenuscene_p.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/cooperationutil_p.h
src/plugins/cooperation/transfer/global_defines.h
src/plugins/cooperation/transfer/utils/transferhelper.cpp
src/plugins/cooperation/transfer/utils/transferhelper_p.h
src/plugins/daemon/core/service/comshare.h

feat: file transfer

---

3rdparty/zrpc/include/rpcchannel.h
3rdparty/zrpc/src/spec/rpcchannel.cpp
src/plugins/daemon/core/service/job/communicationjob.cpp
src/plugins/daemon/core/service/job/communicationjob.h
src/plugins/daemon/core/service/servicemanager.cpp

Modifying transmission failures, and not connecting to the remote end
Log: Modifying transmission failures, and not connecting to the remote end

feat: Modifying transmission failures, and not connecting to the remote end

---

src/plugins/cooperation/transfer/utils/transferhelper.cpp

fix: fix issue of transfer

---

src/plugins/data-transfer/core/gui/getbackup/drapwindowsdata.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.h
src/plugins/data-transfer/core/gui/getbackup/zipfileprocesswidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.h
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/gui/type_defines.h
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

delete license widget ande change the way to obtain IP in Windows
Log: delete license widget ande change the way to obtain IP in Windows

fix: [ui] fix some window ui bug

---

src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/session.cpp
src/plugins/data-transfer/core/utils/settinghepler.cpp

It must call ipc in coroutine, use UNIGO for call method.
Log: fix bug.

Fix: fix ipc call for win

---

src/plugins/daemon/core/service/job/communicationjob.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h

Modify send request file transfer 3 times, add send to client logs
Log: Modify send request file transfer 3 times, add send to client logs

feat: Modify send request file transfer 3 times, add send to client logs

---

src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocesswidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/transferhepler.h

window build error
Log: window build error

fix: [win] window build error

---

debian/changelog

Tag v0.3.6 for release.
Log: new tag.

chore: New tag

---

src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp

fix outOfStorage logic
Log: fix outOfStorage logic

fix: [outOfStorage] fix outOfStorage logic

---

debian/changelog

v0.3.7 release
Log: v0.3.7 release

chore: v0.3.7 release

---

src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.h.autosave
src/plugins/data-transfer/core/gui/getbackup/drapwindowsdata.cpp
src/plugins/data-transfer/core/gui/getbackup/drapwindowsdata.h
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/calculatefilesize.cpp
src/plugins/data-transfer/core/gui/select/calculatefilesize.h
src/plugins/data-transfer/core/gui/select/configselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.h
src/plugins/data-transfer/core/gui/select/item.cpp
src/plugins/data-transfer/core/gui/select/selectmainwidget.cpp
src/plugins/data-transfer/core/gui/select/userselectfilesize.cpp
src/plugins/data-transfer/core/gui/select/userselectfilesize.h
src/plugins/data-transfer/core/gui/win/devicelistener.cpp
src/plugins/data-transfer/core/gui/win/devicelistener.h
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferworker.h

Add USB plug-and-play detection functionality
Log: Add USB plug-and-play detection functionality

feat: [windows] Add USB plug-and-play detection functionality

---

debian/dde-cooperation-transfer.install
src/external/dde-file-manager-plugins/cooperation/cooperationplugin.cpp
src/external/dde-file-manager-plugins/cooperation/cooperationplugin.h
src/external/dde-file-manager-plugins/cooperation/cooperationplugin.json
src/external/dde-file-manager-plugins/cooperation/menu/cooperationmenuscene.cpp
src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/sortfilterworker.cpp
src/plugins/cooperation/transfer/utils/transferhelper.cpp
src/plugins/cooperation/transfer/utils/transferhelper_p.h

as title
Log: Move the menu item to "share"

feat: Move the menu item to "share"

---

src/external/dde-file-manager-plugins/cooperation/menu/cooperationmenuscene.cpp

the menu of "file transfer" is invaild
Log: fix issue

fix: fix issue of menu

---

src/apps/daemon/service/cooperation-daemon.service

Adjust the Wantedby value in the .service file to default.target.

fix: Fix service not auto start

---

src/plugins/cooperation/core/gui/widgets/buttonboxwidget.cpp
src/plugins/cooperation/core/gui/widgets/deviceitem.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/cooperationutil.h

Change the path for storing logs and the path for receiving files
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-228069.html

fix: Change the path for storing logs and the path for receiving files

---

src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/connect/readywidget.h
src/plugins/data-transfer/core/gui/select/selectmainwidget.cpp
src/plugins/data-transfer/core/utils/transferhepler.h
src/plugins/data-transfer/core/utils/transferworker.cpp

add connect failed signal
Log: add connect failed signal

feat: [ui]add connect failed signal

---

src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/backupload/unzipwoker.h
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.h
src/plugins/data-transfer/core/utils/settinghepler.cpp
src/plugins/data-transfer/core/utils/settinghepler.h
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h

fix some bug about prgress ,uzip ,setting...
Log: fix some bug about prgress ,uzip ,setting...

fix: [bug] fix some bug

---

3rdparty/zrpc/include/rpcchannel.h
3rdparty/zrpc/src/spec/rpcchannel.cpp

Fix the bug of invalid second connection
Log: Fix the bug of invalid second connection

fix: [connect]fix the bug of invalid second connection

---

debian/changelog

chore: [tag]v0.3.8

---

3rdparty/zrpc/include/rpcchannel.h
3rdparty/zrpc/src/spec/rpcchannel.cpp
src/common/comonstruct.h
src/common/comonstruct.proto
src/ipc/proto/chan.h
src/ipc/proto/chan.proto
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/daemon/core/service/fsadapter.cpp
src/plugins/daemon/core/service/fsadapter.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/service/jobmanager.cpp
src/plugins/daemon/core/service/jobmanager.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp

Debugging back-end communication code
Log: Debugging back-end communication code

feat: Debugging back-end communication code

---

src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/transfer/transferhelper_p.h
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

fix: fix issue of infomations

---

src/ipc/proto/backend.h
src/ipc/proto/backend.proto
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp

Network sends too fast, causing the entire system to lag
Log: Dropping files over 10GB can make the system very laggy
Bug: https://pms.uniontech.com/bug-view-228127.html

fix: Dropping files over 10GB can make the system very laggy

---

src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/daemon/core/service/jobmanager.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/sendrpcservice.h

Cooperation-transfer accepts files and receives no progress.
Log: Cooperation-transfer accepts files and receives no progress.

fix: Cooperation-transfer accepts files and receives no progress.

---

src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/choosewidget.h
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.h
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.h
src/plugins/data-transfer/core/gui/select/configselectwidget.cpp
src/plugins/data-transfer/core/gui/select/configselectwidget.h
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.h
src/plugins/data-transfer/core/gui/select/selectmainwidget.cpp
src/plugins/data-transfer/core/gui/select/selectmainwidget.h
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/optionsmanager.cpp
src/plugins/data-transfer/core/utils/optionsmanager.h

clear user selection widget
Log: clear user selection widget

feat: [ui]clear user selection widget

---

src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/transfer/transferhelper_p.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/cooperationutil.h

1.not allow for discovery
2.save dir name
Log: fix issue

fix: fix some issues

---

src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/plugins/daemon/core/service/rpc/sendrpcservice.h

Modify the ping code mechanism to modify the back-end crash problem
Log: Modify the ping code mechanism to modify the back-end crash problem

fix: 修改ping的代码机制，修改后端崩溃问题

---

CMakeLists.txt
src/apps/daemon/main.cpp
src/apps/data-transfer/main.cpp
src/apps/dde-cooperation-transfer/main.cpp
src/apps/dde-cooperation/main.cpp
src/plugins/daemon/core/service/inputcooperation.cpp

Fix the build and runtime issue, add app dir for windows runtime.
Log: fix bug.

fix: Fix runtime issue

---

src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/dialogs/settingdialog_p.h
src/plugins/cooperation/core/gui/widgets/deviceitem.cpp
src/plugins/cooperation/core/gui/widgets/deviceitem.h
src/plugins/cooperation/core/gui/widgets/devicelistwidget.cpp
src/plugins/cooperation/core/gui/widgets/devicelistwidget.h
src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/gui/widgets/workspacewidget_p.h
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/transfer/transferhelper_p.h
src/plugins/cooperation/core/utils/historymanager.cpp
src/plugins/cooperation/core/utils/historymanager.h
src/plugins/cooperation/core/utils/sortfilterworker.cpp
src/plugins/cooperation/core/utils/sortfilterworker.h

add history info for transfer
Log: feature

feat: transfer history

---

src/common/comonstruct.h
src/common/comonstruct.proto
src/common/constant.h
src/ipc/proto/backend.h
src/ipc/proto/backend.proto
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.h
src/plugins/daemon/core/service/ipc/session.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/service/jobmanager.cpp
src/plugins/daemon/core/service/jobmanager.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp

If the user cancel the transfering job, it notifies the remote job canceled and stop local job.
Log: Support cancel job.

feat: Implement job cancel

---

src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/choosewidget.h
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/connect/promptwidget.cpp
src/plugins/data-transfer/core/gui/connect/promptwidget.h
src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
translations/data-transfer/deepin-data-transfer.ts
translations/data-transfer/deepin-data-transfer_zh_CN.ts

fix dark theme ui bug and fix Chinese translation
Log: fix dark theme ui bug and fix Chinese translation

fix: [ui]fix dark theme ui bug and fix Chinese translation

---

src/common/commonstruct.h
src/common/commonstruct.proto
src/ipc/backendservice.cpp
src/ipc/backendservice.h
src/ipc/bridge.h
src/ipc/frontendservice.cpp
src/ipc/frontendservice.h
src/ipc/proto/backend.h
src/ipc/proto/backend.proto
src/ipc/proto/comstruct.h
src/ipc/proto/comstruct.proto
src/ipc/proto/frontend.h
src/ipc/proto/frontend.proto
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/daemon/utils/cooperationutil.cpp
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/fsadapter.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.h
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/jobmanager.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/rpc/handlesendresultservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.h

Packaging shared mouse and keyboard
Log: Packaging shared mouse and keyboard

feat: Packaging shared mouse and keyboard

---

src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/share/sharemanager.cpp
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/sortfilterworker.cpp
src/plugins/cooperation/daemon/utils/cooperationutil.cpp

1.change the session name
2.After a long standby period, the device cannot be discovered
Log: fix issue

fix: fixed file transfer issue

---

src/plugins/data-transfer/core/utils/settinghepler.cpp

fix setting desult description too long
Log: fix setting desult description too long
Bug: https://pms.uniontech.com/bug-view-227145.html

fix: [setting] fix setting desult description too long

---

src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.h
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.h
src/plugins/data-transfer/core/gui/win/drapwindowsdata.cpp
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/optionsmanager.h
src/plugins/data-transfer/core/utils/transferworker.cpp

fix backup file bug
Log: fix backup file bug

fix: [backupfile] fix backup file bug

---

src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h

After entering standby, upd exits sending
Log: After waking up from standby and starting cross-end collaboration, other devices can't search for this device.
Bug: https://pms.uniontech.com/bug-view-229255.html

fix: After waking up from standby and starting cross-end collaboration, other devices can't search for this device.

---

src/plugins/daemon/core/utils/utils.h
src/plugins/data-transfer/core/utils/transferworker.cpp

Fix datatransfer cancel job and network IP issue.
Log: fix bug.

fix: Fix datatransfer cancel job

---

src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/utils/historymanager.cpp
src/plugins/cooperation/core/utils/historymanager.h
src/plugins/cooperation/core/utils/sortfilterworker.cpp
src/plugins/cooperation/core/utils/sortfilterworker.h
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp

Devices with a delivery history are ranked first
Log: Optimal sorting algorithm

chore: Optimal sorting algorithm

---

src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h
src/plugins/data-transfer/core/utils/transferworker.cpp

Implement continue last not done job, part 1.
Log: Implement datatransfer continue last not done job.

feat: [dt]Implement continue last not done job

---

3rdparty/CMakeLists.txt
src/common/commonstruct.h
src/common/commonstruct.proto
src/ipc/bridge.h
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/share/sharecooperationservice.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.h
src/plugins/daemon/core/utils/cooconfig.h

Backend keyboard and mouse shared code completed
Log: Backend keyboard and mouse shared code completed

feat: Backend keyboard and mouse shared code completed

---

src/plugins/cooperation/CMakeLists.txt
src/plugins/cooperation/core/CMakeLists.txt
src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/gui/dialogs/transferdialog.cpp
src/plugins/cooperation/core/maincontroller/linux/maincontroller_linux.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.h
src/plugins/cooperation/core/maincontroller/win/maincontroller_win.cpp
src/plugins/cooperation/core/proxy/cooperationdialog.cpp
src/plugins/cooperation/core/proxy/cooperationdialog.h
src/plugins/cooperation/core/proxy/cooperationproxy.cpp
src/plugins/cooperation/core/proxy/cooperationproxy.h
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

as title
Log: add transfer dialog for windows

feat: add transfer dialog for windows

---

3rdparty/barrier/CMakeLists.txt
3rdparty/barrier/src/lib/base/Event.h
3rdparty/barrier/src/lib/common/common.h
3rdparty/barrier/src/lib/io/StreamBuffer.cpp
3rdparty/barrier/src/lib/net/FingerprintData.h
debian/control

fix ci build which caused by barrier needs the curl depend.
Log: fix build issue.

fix: [build] Fix barrier build issue

---

src/common/commonutils.h
src/plugins/cooperation/core/CMakeLists.txt
src/plugins/cooperation/core/gui/widgets/devicelistwidget.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/proxy/cooperationdialog.cpp
src/plugins/daemon/core/CMakeLists.txt
src/plugins/daemon/core/utils/utils.h
src/plugins/data-transfer/core/CMakeLists.txt
src/plugins/data-transfer/core/utils/transferhepler.cpp

fix some windows network check
Log: fix some windows network check

fix: [win] fix some windows network check

---

src/common/commonstruct.h
src/common/commonstruct.proto
src/ipc/bridge.h
src/ipc/frontendservice.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.h

Modify keyboard and mouse sharing
Log: Modify keyboard and mouse sharing

feat: Modify keyboard and mouse sharing

---

src/common/constant.h
src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationmanager.h
src/plugins/cooperation/core/cooperation/cooperationmanager_p.h
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.cpp
src/plugins/cooperation/core/gui/mainwindow.cpp
src/plugins/cooperation/core/gui/mainwindow.h
src/plugins/cooperation/core/gui/widgets/devicelistwidget.cpp
src/plugins/cooperation/core/gui/widgets/devicelistwidget.h
src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/gui/widgets/workspacewidget.h
src/plugins/cooperation/core/gui/widgets/workspacewidget_p.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/sortfilterworker.cpp
src/plugins/cooperation/core/utils/sortfilterworker.h

Added some interactive logic
Log: new feature

feat: peripheral share

---

src/ipc/backendservice.cpp
src/ipc/backendservice.h
src/ipc/bridge.h
src/ipc/proto/backend.h
src/ipc/proto/backend.proto
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp

Add disconnection interface
Log: Add disconnection interface

feat: Add disconnection interface

---

src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationmanager_p.h
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/data-transfer/core/gui/select/item.cpp
src/plugins/data-transfer/core/gui/select/siderbarwidget.cpp

fix ui logic
Log: fix ui logic

fix: [ui] fix ui logic

---

3rdparty/zrpc/src/spec/rpcchannel.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.h
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

fix transfer disconnect
Log: fix transfer disconnect

fix: [transfer disconnect] fix transfer disconnect

---

src/plugins/data-transfer/core/utils/settinghepler.cpp

fix without json file ,no tip
Log: fix without json file ,no tip

fix: [setting]fix without json file ,no tip

---

src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/proxy/cooperationproxy.cpp
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/daemon/utils/cooperationutil.cpp
src/plugins/daemon/core/daemoncoreplugin.cpp
src/plugins/data-transfer/core/datatransfercoreplugin.cpp
src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/calculatefilesize.cpp
src/plugins/data-transfer/core/gui/select/configselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/select/selectmainwidget.cpp
src/plugins/data-transfer/core/gui/select/siderbarwidget.cpp
src/plugins/data-transfer/core/gui/win/devicelistener.cpp
src/plugins/data-transfer/core/gui/win/drapwindowsdata.cpp
src/plugins/data-transfer/core/utils/settinghepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

Use the co log replace Qt logs, that implement journal logs.
Log: Format logs.

chore: [log] Replace Qt log outputs

---

debian/changelog

new version 0.4.1 release.
Log: v0.4.1 release.

chore: v0.4.1 release

---

src/apps/data-transfer/setup/win/datatransfer-setup.iss
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/utils/config.h

If transfer many file once time, it always broken.
Log: fix bug.

fix: Fix transfer many files broken issue

---

src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationmanager.h
src/plugins/cooperation/core/cooperation/cooperationmanager_p.h
src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/info/deviceinfo.cpp
src/plugins/cooperation/core/info/deviceinfo.h
src/plugins/cooperation/core/info/deviceinfo_p.h
src/plugins/cooperation/core/maincontroller/linux/maincontroller_linux.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/core/utils/cooperationutil.h
src/plugins/cooperation/core/utils/historymanager.cpp
src/plugins/cooperation/core/utils/historymanager.h
src/plugins/cooperation/core/utils/sortfilterworker.cpp
src/plugins/cooperation/core/utils/sortfilterworker.h

1.as title
2.Perfect interaction logic
3.Optimize the sorting rules of the device list
Log: Peripheral sharing

feat: Peripheral sharing

---

src/plugins/cooperation/core/cooperation/cooperationmanager.cpp

fix: Fix compilation errors

---

debian/changelog

new tag 0.4.2 release
Log: v0.4.2

chore: [tag]v0.4.2

---

src/common/commonstruct.h
src/common/commonstruct.proto
src/common/constant.h
src/ipc/proto/comstruct.h
src/ipc/proto/comstruct.proto
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/discoveryjob.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/sendipcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.h
src/plugins/daemon/core/service/share/sharecooperationservicemanager.cpp
src/plugins/daemon/core/service/share/sharecooperationservicemanager.h

Keymouse shared backend adjustment
Log: Keymouse shared backend adjustment

feat: Keymouse shared backend adjustment

---

src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h

auto connect ipc
Log: fix ipc disconnect

fix: [ipc] fix ipc disconnect

---

3rdparty/coost/include/co/log.h
3rdparty/coost/src/log/log.cc
src/base/baseutils.cpp
src/base/baseutils.h
src/common/commonutils.cpp
src/common/commonutils.h
src/common/constant.h
src/plugins/cooperation/core/CMakeLists.txt
src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/cooperationcoreplugin.h
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/daemon/CMakeLists.txt
src/plugins/cooperation/daemon/daemoncooperationplugin.cpp
src/plugins/daemon/core/CMakeLists.txt
src/plugins/daemon/core/daemoncoreplugin.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/session.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/plugins/data-transfer/core/CMakeLists.txt
src/plugins/data-transfer/core/datatransfercoreplugin.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h

Enable config detail logs output via parameter.
Log: Enable detail log via param.

feat: [log]Support detail log

---

src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h
src/plugins/data-transfer/core/utils/transferworker.cpp

after transfer , no emit disconnect signals
Log: fix rpc disconnect logic

fix: [disconnect tip] fix rpc disconnect logic

---

debian/changelog
debian/deepin-data-transfer.install
src/apps/data-transfer/CMakeLists.txt
src/apps/data-transfer/setup/linux/deepin-data-transfer.json

New tag 0.4.3 and add log json config file.
Log: new tag 0.4.3

chore: New tag 0.4.3 and add log json

---

3rdparty/coost/src/CMakeLists.txt
debian/control
src/apps/dde-cooperation/setup/linux/dde-cooperation.json

Change the dde-cooperation depend to dde-cooperation-transfer, and add log config file for dde-cooperation.
Log: Change depends and add log config.

chore: [coo]Change depends and add log config

---

src/plugins/daemon/core/service/searchlight.cpp

It return if join multicast group failed, then cause the discover server stop forever.
Log: fix discover stop.

fix: Fix discover stop

---

src/plugins/daemon/core/service/fsadapter.cpp
src/plugins/daemon/core/service/fsadapter.h
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/service/searchlight.cpp

Collecting duplicate files will overwrite them
Log: Collecting duplicate files will overwrite them
Bug: https://pms.uniontech.com/bug-view-231797.html

fix: Collecting duplicate files will overwrite them

---

src/apps/dde-cooperation/main.cpp
src/external/dde-file-manager-plugins/cooperation/CMakeLists.txt
src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationmanager.h
src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

1.Fixed translation issues
2.When the application exits, the sharing is stopped 3.Fixed an issue where devices with the same name could not be shared 4.Fixed an issue where devices could still be found after network disconnection
Log: fix issues
Bug: https://pms.uniontech.com/bug-view-233141.html
Bug: https://pms.uniontech.com/bug-view-233119.html
Bug: https://pms.uniontech.com/bug-view-233117.html
Bug: https://pms.uniontech.com/bug-view-232939.html
Bug: https://pms.uniontech.com/bug-view-232945.html

fix: fixed some issues

---

src/apps/dde-cooperation/main.cpp
src/plugins/cooperation/core/gui/win/cooperationsearchedit.cpp
src/plugins/cooperation/core/gui/win/cooperationsearchedit.h

Fix build failed issue on win.
Log: fix win build.

fix: [build] Fix win build

---

src/apps/data-transfer/setup/win/datatransfer-setup.iss
src/apps/dde-cooperation/setup/win/cooperation-setup.iss
src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.cpp

It can not launch process on win, use diff API to fix it, and fix some crash issue on win.
Log: Fix process launch issue.

fix: Fail to start process on win

---

src/plugins/daemon/core/service/fsadapter.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.cpp
src/plugins/daemon/core/service/share/sharecooperationservice.h
src/plugins/daemon/core/service/share/sharecooperationservicemanager.cpp
src/plugins/daemon/core/service/share/sharecooperationservicemanager.h

https://pms.uniontech.com/bug-view-233251.html
键鼠共享不稳定

fix some bug

---

debian/changelog

new tag v0.4.4 release.
Log: v0.4.4

chore: [tag]new tag v0.4.4

---

src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.cpp
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.h
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

feat: Add the Windows Interactive interface

---

src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.cpp
src/plugins/cooperation/core/utils/cooperationutil.cpp

fix some win bug
LOG: fix some win bug

fix: [win] fix some win bug

---

src/apps/dde-cooperation/main.cpp
src/apps/dde-cooperation/setup/win/cooperation.vbs
src/common/constant.h
src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationmanager.h
src/plugins/cooperation/core/cooperation/cooperationmanager_p.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-233775.html

fix: When the application exits, the connection is not disconnected

---

src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.cpp
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.h
src/plugins/cooperation/core/cooperationcoreplugin.cpp

fix: fixed translation issue on windows

---

src/plugins/data-transfer/core/utils/settinghepler.cpp
translations/deepin-data-transfer/deepin-data-transfer.ts
translations/deepin-data-transfer/deepin-data-transfer_zh_CN.ts

progress translate error
Log: progress translate error

fix: [translate] progress translate error

---

src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp

[unzip] fix unzip bug in U disk
Log: [unzip] fix unzip bug in U disk

fix: [unzip] fix unzip bug in U disk

---

src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationtaskdialog.cpp
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/dialogs/settingdialog_p.h
src/plugins/cooperation/core/gui/dialogs/transferdialog.cpp
src/plugins/cooperation/core/gui/widgets/buttonboxwidget.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/cooperation/core/gui/widgets/deviceitem.cpp
src/plugins/cooperation/core/gui/widgets/devicelistwidget.cpp
src/plugins/cooperation/core/gui/widgets/settingitem.cpp
src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/utils/cooperationguihelper.cpp
src/plugins/cooperation/core/utils/cooperationguihelper.h
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

Only one device can be connected at a time
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-234097.html

fix: Once connected, the device can also connect to other devices

---

src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/cooperation/core/gui/widgets/deviceitem.cpp
src/plugins/cooperation/core/gui/widgets/deviceitem.h
src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/utils/cooperationguihelper.cpp
src/plugins/cooperation/core/utils/sortfilterworker.cpp
src/plugins/cooperation/core/utils/sortfilterworker.h

Fixed font color issues
Log: fix issue

fix: [UI] fix UI issue

---

src/common/commonstruct.h
src/common/commonstruct.proto
src/common/constant.h
src/ipc/proto/chan.h
src/ipc/proto/chan.proto
src/ipc/proto/frontend.h
src/ipc/proto/frontend.proto
src/plugins/cooperation/core/proxy/cooperationproxy.cpp
src/plugins/cooperation/core/proxy/cooperationproxy.h
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/transfer/transferhelper_p.h
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.h
src/plugins/daemon/core/service/fsadapter.cpp
src/plugins/daemon/core/service/fsadapter.h
src/plugins/daemon/core/service/ipc/session.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h
src/plugins/daemon/core/service/jobmanager.cpp
src/plugins/daemon/core/service/jobmanager.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.h
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h

Integrate the new block transfer solution which fix some tranfer issues.
Log: Integrate new transfer solution.

Integrate the new block transfer solution

---

3rdparty/coost/src/log/log.cc
debian/dde-cooperation.install
src/apps/dde-cooperation/CMakeLists.txt

[log] Adapt deepin logging tools
Log: [log] Adapt deepin logging tools

fix: [log] Adapt deepin logging tools

---

src/common/commonstruct.h
src/common/commonstruct.proto
src/ipc/proto/chan.h
src/ipc/proto/chan.proto
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/job/transferjob.h

The send file info is incorrect, refactor codes which add rootdir for it.
Log: Fix incorrect file path.

fix: [trans]Fix incorrect file path

---

src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/icon/tab_close_normal.svg
src/plugins/data-transfer/core/utils/settinghepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

fix some ui bug
Log: fix some ui bug

fix: [ui] fix some ui bug

---

debian/changelog
debian/control
debian/source/lintian-overrides
src/apps/data-transfer/setup/win/datatransfer-setup.iss
src/apps/dde-cooperation/setup/win/cooperation-setup.iss

new tag v0.5.0
Log: v0.5.0 release.

chore: [tag]v0.5.0

---

src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp

as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-234521.html

fix: [UI] The picture does not change with the theme

---

src/base/reportlog/datas/cooperationreportdata.cpp
src/base/reportlog/datas/cooperationreportdata.h
src/base/reportlog/datas/reportdatainterface.h
src/base/reportlog/reportlogmanager.cpp
src/base/reportlog/reportlogmanager.h
src/base/reportlog/reportlogworker.cpp
src/base/reportlog/reportlogworker.h
src/plugins/cooperation/core/CMakeLists.txt
src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/cooperation/core/cooperation/cooperationmanager_p.h
src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/cooperationcoreplugin.h
src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/info/deviceinfo.cpp
src/plugins/cooperation/core/info/deviceinfo.h
src/plugins/cooperation/core/info/deviceinfo_p.h
src/plugins/cooperation/core/maincontroller/maincontroller.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.h
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/core/transfer/transferhelper_p.h
src/plugins/cooperation/core/utils/cooperationutil.cpp

1. add file transfer log
2. add cooperation log
Log: new feature
Task: https://pms.uniontech.com/task-view-296721.html

feat: add report log feature

---

src/dde-cooperation-translate.sh
src/plugins/cooperation/core/proxy/cooperationproxy.cpp
src/plugins/cooperation/core/proxy/cooperationproxy.h
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.h
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

as title
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-233159.html

fix: The receiving end lacks a timeout message

---

src/plugins/daemon/core/service/rpc/remoteservice.cpp
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.h
src/plugins/data-transfer/core/utils/settinghepler.cpp

fix: [ui] fix some ui bug
Log: fix: [ui] fix some ui bug

fix: [ui] fix some ui bug 28

---

3rdparty/coost/include/co/time.h
3rdparty/coost/src/co/io_event.cc
3rdparty/coost/src/so/ssl.cc
3rdparty/coost/src/time.cc
3rdparty/zrpc/src/net/tcpconnection.cpp
3rdparty/zrpc/src/net/tcpconnection.h
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

The sync network connection cause many issues, it can not be interrupted. Implement SSL async socket.
Log: fix network issue.

fix: Fix network broken issues.

---

src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

Miss handle ping and notify status if failed.
Log: Fix ping offline.

fix: Fix ping offline

---

src/plugins/data-transfer/core/gui/mainwindow.cpp
src/plugins/data-transfer/core/gui/mainwindow.h
src/plugins/data-transfer/core/gui/mainwindow_p.h
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp

now only press titlebar to move mainwindows
LOG: fix: [move] fix move mainwindow error

fix: [move] fix move mainwindow error

---

3rdparty/zrpc/src/net/tcpconnection.cpp
src/common/commonstruct.h
src/common/commonstruct.proto
src/common/constant.h
src/ipc/proto/chan.h
src/plugins/daemon/core/service/ipc/sendipcservice.cpp
src/plugins/daemon/core/service/ipc/sendipcservice.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/plugins/daemon/core/service/rpc/sendrpcservice.h

The offline status maybe incorrect by sometime, add a cache to cancel this case.
Log: Fix offline unstable.

fix: Fix remote offline unstable

---

3rdparty/zrpc/src/net/tcpconnection.h
src/plugins/data-transfer/core/utils/transferworker.cpp

The timeout 1s is too short to connection can not be created.
Log: fix connect issue.

fix: Fix transfer disconnect at first time

---

.tx/config
.tx/deepin.conf
src/translate_desktop2ts.sh
src/translate_ts2desktop.sh
translations/dde-cooperation-desktop/desktop.ts
translations/dde-cooperation-desktop/desktop_zh_CN.ts
translations/deepin-data-transfer-desktop/desktop.ts
translations/deepin-data-transfer-desktop/desktop_zh_CN.ts

to adapt the languages
Log: to adapt the languages
Bug: no

doc: add languages setting

---

debian/changelog
src/apps/data-transfer/setup/win/datatransfer-setup.iss
src/apps/dde-cooperation/setup/win/cooperation-setup.iss

new tag v0.5.5
Log: v0.5.5 release.

chore: [tag]v0.5.5

---

debian/control
src/common/commonstruct.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp

Fix incorrect json and package conflicts.
Log: fix package conflicts.

fix: Fix incorrect json and package conflicts

---

src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp

Set setting window to model
Log: Set setting window to model

fix: Set setting window to model

---

.tx/config
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/deepin-data-transfer/deepin-data-transfer.ts
translations/deepin-data-transfer/deepin-data-transfer_zh_CN.ts

fix lanuage setting
Log: fix lanuage setting
Bug: no

fix: fix lanuage setting

---

src/ipc/proto/chan.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp

Add error handling parameters
Log: Add error handling parameters

fix: Add error handling parameters

---

3rdparty/zrpc/src/net/tcpconnection.cpp
src/apps/daemon/main.cpp
src/apps/daemon/service/cooperation-daemon.service
src/apps/data-transfer/main.cpp
src/common/commonutils.cpp
src/common/commonutils.h
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/discoveryjob.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h

Only launch daemon for actived login user. Do not send offline if read 0 data from socket.
Log: Only launch daemon for actived user.

fix: Fix mutil-user launch

---

src/apps/daemon/main.cpp

Fix can not get actived user.
Log: Fix can not get actived user.

fix: Fix can not get actived user

---

debian/changelog
src/apps/daemon/CMakeLists.txt
src/apps/daemon/res/win/admin.manifest
src/apps/daemon/res/win/daemon.rc
src/apps/data-transfer/setup/win/datatransfer-setup.iss
src/apps/dde-cooperation/setup/win/cooperation-setup.iss

The daemon require admin to run in order to barrierc has enough right. Add new tag v0.5.6.
Log: build deamon as admin.

fix: run daemon with admin for win

---

debian/changelog

chore: [tag] v0.5.7

---

debian/changelog

v0.5.6.5
Log: v0.5.6.5 release.

chore: [tag] v0.5.6.5

---

src/apps/daemon/main.cpp

Optimize to obtain the current active user
Log: Optimize to obtain the current active user

fix: Optimize to obtain the current active user

---

src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/cooperationcoreplugin.h
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/dialogs/settingdialog_p.h
src/plugins/cooperation/core/utils/cooperationutil.cpp

[Event Tracking] change Event Tracking  logic
Log: [Event Tracking] change Event Tracking  logic

feat: [Event Tracking] change Event Tracking  logic

---

src/apps/daemon/main.cpp

Remove string length judgment
Log: Cooperation-daemon failed to start

fix: Cooperation-daemon failed to start

---

debian/changelog

chore: [tag] v0.5.8

---

src/plugins/cooperation/core/cooperation/cooperationmanager.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/select/fileselectwidget.h
src/plugins/data-transfer/core/gui/select/item.cpp
src/plugins/data-transfer/core/gui/select/item.h
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/utils/settinghepler.cpp

fix: [ui] fix ui 116

---

src/apps/daemon/main.cpp
src/common/constant.h
src/plugins/daemon/core/service/servicemanager.cpp
src/plugins/daemon/core/service/servicemanager.h

Switching user crashes
Log: Switching user crashes
Bug: https://pms.uniontech.com/bug-view-238377.html

fix: Switching user crashes

---

src/plugins/data-transfer/core/gui/backupload/unzipwoker.cpp
src/plugins/data-transfer/core/utils/settinghepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp

remove retransfeer temp file
Log: [retransfer] fix retransfer temp file

fix: [retransfer] fix retransfer temp file

---

.github/workflows/windows-mingw.yml
3rdparty/quazip/CMakeLists.txt
dist/inno/scripts/lang/ChineseSimplified.isl
dist/inno/scripts/lang/chinese.iss
dist/inno/scripts/lang/deepin-cooperation.iss
dist/inno/scripts/lang/deepin-datatransfer.iss
src/plugins/cooperation/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/gui/select/siderbarwidget.cpp

add CI release for windows.
Log: add CI release for windows.

chore: [CI]add CI release for windows

---

debian/changelog

new tag v0.6.0.
Log: v0.6.0 release.

chore: [tag]v0.6.0

---

src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.h
src/plugins/data-transfer/core/gui/connect/networkdisconnectionwidget.cpp
src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/connect/startwidget.cpp
src/plugins/data-transfer/core/gui/connect/startwidget.h
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.h
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.h
src/plugins/data-transfer/core/gui/select/configselectwidget.cpp
src/plugins/data-transfer/core/gui/select/configselectwidget.h
src/plugins/data-transfer/core/gui/select/fileselectwidget.cpp
src/plugins/data-transfer/core/gui/select/selectmainwidget.cpp
src/plugins/data-transfer/core/gui/select/selectmainwidget.h
src/plugins/data-transfer/core/gui/transfer/errorwidget.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/gui/transfer/waittransferwidget.cpp
src/plugins/data-transfer/core/gui/transfer/waittransferwidget.h
src/plugins/data-transfer/core/gui/type_defines.cpp
src/plugins/data-transfer/core/gui/type_defines.h

Unified control UI style
Log: Unified control UI style

fix: [ui] Unified control UI style

---

debian/changelog

new tag v0.6.1.
Log: v0.6.1 release.

chore: [tag]v0.6.1

---

src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/connect/networkdisconnectionwidget.cpp
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.h
src/plugins/data-transfer/core/gui/type_defines.cpp
src/plugins/data-transfer/core/gui/type_defines.h

fix ui bug 122
Log:  fix ui bug 122

fix: [ui] fix ui bug 122

---

src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
translations/dde-cooperation-desktop/desktop_zh_CN.ts
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/deepin-data-transfer-desktop/desktop_zh_CN.ts
translations/deepin-data-transfer/deepin-data-transfer.ts
translations/deepin-data-transfer/deepin-data-transfer_zh_CN.ts

fix translation
Log: fix translation

fix: [translation] fix translation

---

debian/changelog

new tag v0.6.2.
Log: v0.6.2 release.

chore: [tag]v0.6.2

---

src/plugins/cooperation/core/global_defines.h
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/dialogs/settingdialog.h
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocesswidget.cpp
src/plugins/data-transfer/core/gui/select/appselectwidget.cpp
src/plugins/data-transfer/core/gui/select/configselectwidget.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp

fix: [ui] fix ui 1.25

---

debian/changelog

new tag v0.6.3
Log: v0.6.3 release.

chore: [tag]v0.6.3

---

src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp

[buildpackage] error
Log: fix: [buildpackage] error

fix: [buildpackage] error

---

src/ipc/backendservice.cpp
src/ipc/backendservice.h
src/ipc/bridge.h
src/ipc/frontendservice.cpp
src/ipc/frontendservice.h
src/ipc/proto/backend.h
src/ipc/proto/backend.proto
src/ipc/proto/comstruct.h
src/ipc/proto/comstruct.proto
src/ipc/proto/frontend.h
src/ipc/proto/frontend.proto
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/discoveryjob.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h
src/plugins/data-transfer/core/gui/connect/choosewidget.cpp

search device by ip deamon
Log: search device by ip deamon
Task: https://pms.uniontech.com/task-view-322793.html

feat: search device by ip deamon

---

src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/data-transfer/core/gui/transfer/errorwidget.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.h
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/gui/type_defines.h
src/plugins/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/plugins/data-transfer/core/utils/settinghepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferhepler.h
src/plugins/data-transfer/core/utils/transferworker.cpp

now will back to waittingview and wait next transfer
Log: fix: [finish] change result view back btn logic

fix: [finish] change result view back btn logic

---

src/ipc/backendservice.cpp
src/ipc/backendservice.h
src/ipc/proto/backend.h
src/ipc/proto/backend.proto

get server current status
Log: get server current status

feat: get server current status

---

src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/discoveryjob.h
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h

add search device by ip
Log: add search device by ip

feat: add search device by ip

---

src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h

add search device by ip and notify device online
Log: add search device by ip and notify device online

feat: add search device by ip and notify device online

---

src/common/commonstruct.h
src/ipc/proto/comstruct.h
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/discoveryjob.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.h
src/plugins/daemon/core/service/searchlight.cpp
src/plugins/daemon/core/service/searchlight.h

add discover by tcp
Log: add discover by tcp

feat: add discover by tcp

---

debian/changelog

new tag v0.7.0.
Log: v0.7.0 release.

chore: [tag]v0.7.0

---

src/plugins/daemon/core/service/comshare.cpp
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/discoveryjob.cpp
src/plugins/daemon/core/service/ipc/handleipcservice.cpp

Searching for the wrong IP, changing to the correct one after leaving, requires a long search time
Log: Searching for the wrong IP, changing to the correct one after leaving, requires a long search time

fix: Searching for the wrong IP, changing to the correct one after leaving, requires a long search time

---

src/plugins/cooperation/core/gui/widgets/filechooseredit.cpp
src/plugins/cooperation/core/gui/widgets/filechooseredit.h
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

Log: Add path permission validation when users choose a path,Cancel path selection and display a prompt dialog.
Bug: https://pms.uniontech.com/bug-view-243035.html

fix: Add path permission validation when users choose a path.

---

debian/copyright

update the copyright to match normal license
Log: update the copyright to match normal license
Bug: no

doc: update the copyright to match normal license

---

3rdparty/coost/include/co/log.h
src/common/commonutils.cpp
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/daemon/core/service/fsadapter.cpp
src/plugins/daemon/core/service/fsadapter.h

support dynamic tuning
Log: fix: [log] support dynamic tuning
Bug: https://pms.uniontech.com/bug-view-239851.html

fix: [log] support dynamic tuning

---

src/plugins/cooperation/core/cooperation/cooperationtaskdialog.cpp
src/plugins/cooperation/core/gui/dialogs/transferdialog.cpp
translations/dde-cooperation/dde-cooperation_zh_CN.ts

Log: Adjust the Commit Dialog Size and Modify Translation
Bug: https://pms.uniontech.com/bug-view-241821.html  https://pms.uniontech.com/bug-view-243007.html

fix: Adjust the Commit Dialog Size and Modify Translation

---

3rdparty/coost/include/co/log.h
src/common/commonutils.cpp
src/plugins/cooperation/core/transfer/transferhelper.cpp
src/plugins/cooperation/daemon/maincontroller/maincontroller.cpp
src/plugins/daemon/core/service/fsadapter.cpp
src/plugins/daemon/core/service/jobmanager.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

prompt write block error
Log: fix: [io error] write block error
Bug: https://pms.uniontech.com/my-bug-assignedTo.html

fix: [io error] write block error

---

debian/changelog

new tag v0.7.1
Log:  v0.7.1 release.

chore: [tag]v0.7.1

---

src/plugins/data-transfer/core/CMakeLists.txt
src/plugins/data-transfer/core/gui/getbackup/createbackupfilewidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipfileprocessresultwidget.cpp
src/plugins/data-transfer/core/gui/getbackup/zipworker.cpp
src/plugins/data-transfer/core/gui/icon/workDone.svg
src/plugins/data-transfer/core/gui/icon/working.svg
src/plugins/data-transfer/core/gui/resources.qrc
src/plugins/data-transfer/core/gui/transfer/errorwidget.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.h
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.h
src/plugins/data-transfer/core/gui/type_defines.cpp
src/plugins/data-transfer/core/gui/type_defines.h
translations/deepin-data-transfer/deepin-data-transfer.ts
translations/deepin-data-transfer/deepin-data-transfer_zh_CN.ts

Log: fix the ui bug of dde-data-transfer

fix: [ui]fix the ui bug of dde-data-transfer

---

src/plugins/data-transfer/core/CMakeLists.txt

It did not deploy depends for share library, miss sql drivers.
Log: fix windows setup package miss runtime depends.

Fix: Fix setup package miss depends

---

src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts

fix: [ui] fix ui bug
Log: fix: [ui] fix ui bug
Bug: https://pms.uniontech.com/bug-view-244165.html

fix: [ui] fix ui bug

---

debian/changelog

new tag v0.7.2
Log:  v0.7.2 release.

chore: [tag]v0.7.2

---

src/plugins/data-transfer/core/gui/type_defines.h
src/plugins/data-transfer/core/utils/transferhepler.cpp
src/plugins/data-transfer/core/utils/transferworker.cpp
src/plugins/data-transfer/core/utils/transferworker.h

[retransfer] fix retransfer bug
Log: [retransfer] fix retransfer bug
Bug: https://pms.uniontech.com/bug-view-246087.html

fix: [retransfer] fix retransfer bug

---

debian/changelog

new tag v0.7.3
Log: v0.7.3 release.

chore: [tag]v0.7.3

---

debian/changelog

new tag v0.7.4
Log: v0.7.4 release.

chore: [tag]v0.7.4

---

debian/changelog

new tag v0.7.5
Log: v0.7.5 release.

chore: [tag]v0.7.5

---

debian/changelog

new tag v0.7.6
Log: v0.7.6 release.

chore: [tag]v0.7.6

---

src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
translations/deepin-data-transfer/deepin-data-transfer.ts
translations/deepin-data-transfer/deepin-data-transfer_zh_CN.ts

Add data transfer client download link.
Log: add client download link.

feat: [ui]Add client download link

---

debian/changelog

new tag v0.7.7
Log: v0.7.7 release.

chore: [tag]v0.7.7

---

src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/dialogs/transferdialog.cpp
src/plugins/cooperation/core/gui/dialogs/transferdialog.h
src/plugins/cooperation/core/gui/resources/icons/deepin/builtin/dark/icons/tab_close_normal.svg
src/plugins/cooperation/core/gui/resources/resources.qrc
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.h
src/plugins/cooperation/core/gui/widgets/workspacewidget.cpp
src/plugins/cooperation/core/gui/widgets/workspacewidget_p.h
src/plugins/cooperation/core/gui/win/cooperationsearchedit.cpp
src/plugins/cooperation/core/gui/win/cooperationsearchedit.h
src/plugins/cooperation/core/utils/cooperationutil.cpp
src/plugins/data-transfer/core/gui/backupload/uploadfilewidget.cpp
src/plugins/data-transfer/core/gui/connect/choosewidget.cpp
src/plugins/data-transfer/core/gui/connect/connectwidget.cpp
src/plugins/data-transfer/core/gui/connect/promptwidget.cpp
src/plugins/data-transfer/core/gui/connect/readywidget.cpp
src/plugins/data-transfer/core/gui/connect/startwidget.cpp
src/plugins/data-transfer/core/gui/transfer/errorwidget.cpp
src/plugins/data-transfer/core/gui/transfer/resultdisplay.cpp
src/plugins/data-transfer/core/gui/transfer/transferringwidget.cpp
src/plugins/data-transfer/core/gui/transfer/waittransferwidget.cpp
src/plugins/data-transfer/core/gui/type_defines.cpp
src/plugins/data-transfer/core/gui/type_defines.h
src/singleton/singleapplication.cpp

[fontsize] adjust system font
Log: [fontsize] adjust system font
Bug: https://pms.uniontech.com/bug-view-245169.html

fix: [fontsize] adjust system font

---

3rdparty/coost/src/co/sock_win.cc
src/common/commonutils.cpp

If the first log can not be outputed, there is exception that can not receive remote requestion by unkown reason.
Log: fix backend issue on win.

fix: backend log

---

debian/changelog

new tag v0.7.8
Log: v0.7.8 release.

chore: [tag]v0.7.8

---

src/apps/dde-cooperation/assets/dde-cooperation/cooperation/en_US/cooperation.md
src/apps/dde-cooperation/assets/dde-cooperation/cooperation/zh_CN/cooperation.md
src/apps/dde-cooperation/assets/dde-cooperation/cooperation/zh_HK/cooperation.md
src/apps/dde-cooperation/assets/dde-cooperation/cooperation/zh_TW/cooperation.md
src/plugins/cooperation/core/gui/mainwindow.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp

[link] download link change
Log: [link] download link change
Task: https://pms.uniontech.com/story-view-32599.html

feat: [link] download link change

---

src/common/constant.h
src/ipc/proto/chan.h
src/plugins/daemon/core/service/comshare.h
src/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/plugins/daemon/core/service/job/transferjob.cpp
src/plugins/daemon/core/service/jobmanager.cpp
src/plugins/daemon/core/service/rpc/handlerpcservice.cpp
src/plugins/daemon/core/service/rpc/handlesendresultservice.cpp
src/plugins/daemon/core/service/rpc/remoteservice.cpp

The response data maybe the DISCOVER_BY_TCP, then it can not get correct file transfer response, which cause an exception.
Log: Fix transfer exception on not same sub network.
Bug: https://pms.uniontech.com/bug-view-250183.html

fix: Fix transfer exception on not same sub network.

---

debian/changelog

new tag v0.7.9
Log: v0.7.9 release.

chore: [tag]v0.7.9

---

debian/changelog

new tag v0.7.10
Log: v0.7.10 release.

chore: [tag]v0.7.10

---

src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
src/plugins/cooperation/core/gui/resources/icons/deepin/builtin/icons/clear.svg
src/plugins/cooperation/core/gui/resources/resources.qrc
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.h
translations/dde-cooperation/dde-cooperation_zh_TW.ts

fix: [UI] fix cursor still blinks in the input box
Change the user name after pressing enter, the cursor still blinks in the input box. We fixed.
Log: Change the user name after pressing enter, the cursor still blinks in the input box.
Bug: https://pms.uniontech.com/bug-view-241037.html

fix: [UI] fix cursor still blinks in the input box

---

src/apps/daemon/main.cpp
src/plugins/daemon/core/service/servicemanager.cpp

domain controller username and /home/user name are different
Log: fix username compare false
Bug: https://pms.uniontech.com/bug-view-254505.html

fix: [domain controller] fix username compare false

---

src/apps/daemon/main.cpp
src/apps/dde-cooperation/main.cpp
src/base/baseutils.cpp
src/base/baseutils.h

if port busy ,exit
Log: [port busy] add test in front
Bug: https://pms.uniontech.com/bug-view-254777.html

fix: [port busy] add test in front

---

debian/changelog

new tag v0.7.11
Log: v0.7.11 release.

chore: [tag]v0.7.11

---

src/lib/cooperation/core/gui/dialogs/settingdialog.cpp

fix the color of the search input box
Log: fix the color of the search input box
Bug: https://pms.uniontech.com/bug-view-252341.html

fix: [UI] fix the color of the search input box

---

3rdparty/CppServer/modules/asio.cmake
CMakeLists.txt
src/apps/CMakeLists.txt
src/apps/dde-cooperation/main.cpp
src/common/exportglobal.h
src/lib/CMakeLists.txt
src/lib/common/CMakeLists.txt
src/lib/common/httpweb/syncstatus.h
src/lib/common/manager/CMakeLists.txt
src/lib/common/manager/sessionmanager.h
src/lib/common/proto/CMakeLists.txt
src/lib/cooperation/core/CMakeLists.txt
src/lib/cooperation/core/cooperationcoreplugin.cpp
src/lib/cooperation/core/cooperationcoreplugin.h
src/lib/cooperation/core/discovercontroller/discovercontroller.cpp
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/maincontroller/win/maincontroller_win.cpp
src/lib/data-transfer/core/CMakeLists.txt

Export APIs for shared library and temp disable data-transfer, fix run issue.
Log: fix MSVC build and run issue.

fix: [build] Fix MSVC build and run issue

---

src/plugins/cooperation/core/gui/linux/mainwindow_p_linux.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/plugins/cooperation/core/gui/widgets/cooperationstatewidget.h
src/plugins/cooperation/core/utils/cooperationguihelper.cpp
src/plugins/cooperation/core/utils/cooperationguihelper.h

[ui] fix banner ui bug
Log: [ui] fix banner ui bug
Bug: https://pms.uniontech.com/bug-view-256007.html

fix: [ui] fix banner ui bug

---

src/dde-cooperation-translate.sh
src/lib/cooperation/core/discovercontroller/discovercontroller.cpp
src/lib/cooperation/core/discovercontroller/discovercontroller.h
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/gui/win/mainwindow_p_win.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

[zeroconf] add windows zeroconf daemon test
Log: [zeroconf] add windows zeroconf daemon test

fix: [zeroconf] add windows zeroconf daemon test

---

src/lib/cooperation/core/CMakeLists.txt
src/lib/cooperation/core/cooperation/cooperationmanager.cpp
src/lib/cooperation/core/sharemanager/cooconfig.cpp
src/lib/cooperation/core/sharemanager/cooconfig.h
src/lib/cooperation/core/sharemanager/sharecooperationservice.cpp
src/lib/cooperation/core/sharemanager/sharecooperationservice.h
src/lib/cooperation/core/sharemanager/sharecooperationservicemanager.cpp
src/lib/cooperation/core/sharemanager/sharecooperationservicemanager.h
src/lib/cooperation/core/utils/cooperationutil.cpp
src/lib/cooperation/core/utils/cooperationutil.h

feat: [kvm] add kvm

---

src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/fileserver.h
src/lib/common/httpweb/tokencache.cpp
src/lib/common/httpweb/tokencache.h
src/lib/common/manager/transferworker.cpp
src/lib/data-transfer/core/utils/transferworker.cpp

clean up the unused codes.
Log: remove unused codes.

chore: remove unused codes

---

src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/fileserver.h
src/lib/common/httpweb/syncstatus.h
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/common/manager/transferworker.cpp
src/lib/common/manager/transferworker.h
src/lib/cooperation/core/cooperationcoreplugin.cpp
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/networkutil.h
src/lib/cooperation/core/net/networkutill_p.h
src/lib/cooperation/core/utils/cooperationutil.cpp

Integrate transfer and implement the transfer progress for both server and client, update the speed every second.
Log: Integrate the transfer.

feat: Integrate the transfer with new formwork

---

src/lib/cooperation/core/net/cooconstrants.h
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/sharehelper.h
src/lib/cooperation/core/net/helper/sharehelper_p.h
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.h
src/lib/cooperation/core/net/helper/transferhelper_p.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/networkutil.h
src/lib/cooperation/core/net/noticeutil.cpp
src/lib/cooperation/core/net/noticeutil.h

[notice] add notice util
Log: [notice] add notice util

fix: [notice] add notice util

---

src/lib/cooperation/core/cooperationcoreplugin.cpp
src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/gui/mainwindow.h
src/lib/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/lib/cooperation/core/gui/widgets/cooperationstatewidget.h
src/lib/cooperation/core/gui/widgets/devicelistwidget.cpp
src/lib/cooperation/core/gui/widgets/devicelistwidget.h
src/lib/cooperation/core/gui/widgets/workspacewidget.cpp
src/lib/cooperation/core/gui/widgets/workspacewidget.h
src/lib/cooperation/core/gui/widgets/workspacewidget_p.h
src/lib/cooperation/core/gui/win/mainwindow_p_win.cpp
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/sharehelper_p.h
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper_p.h
src/lib/cooperation/core/net/linux/noticeutil.cpp
src/lib/cooperation/core/net/linux/noticeutil.h
src/lib/cooperation/core/share/cooconfig.cpp
src/lib/cooperation/core/share/sharecooperationservice.cpp
src/lib/cooperation/core/utils/cooperationutil.cpp
src/lib/cooperation/core/utils/cooperationutil.h
src/lib/cooperation/core/utils/cooperationutil_p.h
src/lib/cooperation/core/utils/historymanager.cpp
src/lib/cooperation/core/utils/historymanager.h

[win] notice util adapt to Windows
Log: [win] notice util adapt to Windows

fix: [win] notice util adapt to Windows

---

src/common/constant.h
src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/syncstatus.h
src/lib/common/httpweb/webbinder.cpp
src/lib/common/httpweb/webbinder.h
src/lib/common/manager/CMakeLists.txt
src/lib/common/manager/filesizecounter.cpp
src/lib/common/manager/filesizecounter.h
src/lib/common/manager/sessionmanager.cpp
src/lib/common/manager/sessionmanager.h
src/lib/common/manager/sessionproto.h
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/common/manager/transferworker.cpp
src/lib/common/manager/transferworker.h
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.h
src/lib/cooperation/core/net/helper/transferhelper_p.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/networkutill_p.h
src/lib/data-transfer/core/utils/transferworker.cpp
src/lib/data-transfer/core/utils/transferworker.h

Implement the progress rate for transfer.
Log: Implement the progress rate.

feat: Implement the progress rate

---

src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/discover/discovercontroller.h
src/lib/cooperation/core/discover/discovercontroller_p.h
src/lib/cooperation/core/gui/utils/sortfilterworker.cpp
src/lib/cooperation/core/gui/utils/sortfilterworker.h
src/lib/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/lib/cooperation/core/gui/widgets/workspacewidget.cpp
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/utils/cooperationutil.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

[search] add search device
Log: [search] add search device

fix: [search] add search device

---

src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileclient.h
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/fileserver.h
src/lib/common/manager/sessionmanager.cpp
src/lib/common/manager/sessionmanager.h
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/common/manager/transferworker.cpp
src/lib/common/manager/transferworker.h
src/lib/cooperation/core/net/helper/dialogs/cooperationdialog.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.h
src/lib/cooperation/core/net/helper/transferhelper_p.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/data-transfer/core/utils/transferworker.cpp

It stops all transfer workers if user cancel, and fix some related isses.
Log: Support cancel transfer.

feat: Support cancel transfer

---

src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/discover/discovercontroller.h
src/lib/cooperation/core/discover/discovercontroller_p.h
src/lib/cooperation/core/net/helper/dialogs/cooperationdialog.cpp

Change to be consistent with the design drawings
Log: [ui] fix dialog ui error

fix: [ui] fix dialog ui error

---

src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/sharehelper_p.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/networkutil.h

add share dialog timeout logic
Log: [share] fix share dialog timeout

fix: [share] fix share dialog timeout

---

src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/net/cooconstrants.h
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/networkutil.cpp

If this address can not be ping or unreachable, it always block UI.
Log: Fix unable connection issue.

fix: Fix unable connection issue

---

debian/control
src/lib/cooperation/core/net/helper/dialogs/cooperationdialog.cpp
src/lib/cooperation/core/net/helper/dialogs/cooperationdialog.h
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/sharehelper_p.h
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/networkutil.h
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

add transfer apply cancel
Log: add transfer apply cancel

fix: [ui] add transfer apply cancel

---

3rdparty/CppServer/modules/CppCommon/source/math/math.cpp
3rdparty/CppServer/modules/CppCommon/source/time/timestamp.cpp

Fix i386, loongarch, sw64 build.
Log: Fix build for archs.

fix: [build]Fix build for archs

---

3rdparty/CppServer/source/server/ws/ws.cpp

the ws only support 64 bit OS, make it can build with i386.
Log: Fix i386 build.

fix: [build]Fix i386 build

---

src/lib/data-transfer/core/datatransfercoreplugin.cpp
src/lib/data-transfer/core/gui/transfer/resultdisplay.cpp
src/lib/data-transfer/core/gui/transfer/transferringwidget.cpp
src/lib/data-transfer/core/net/helper/transferhepler.cpp
src/lib/data-transfer/core/net/helper/transferhepler.h
src/lib/data-transfer/core/net/networkutil.cpp
src/lib/data-transfer/core/net/networkutil.h
src/lib/data-transfer/core/net/networkutill_p.h
src/lib/data-transfer/core/net/protoconstants.h
src/lib/data-transfer/core/utils/settinghepler.cpp
src/lib/data-transfer/core/utils/transferutil.cpp
src/lib/data-transfer/core/utils/transferutil.h

[data transfer] add transfer logic
Log: [data transfer] add transfer logic

fix: [data transfer] add transfer logic

---

src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/discover/discovercontroller.h
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/networkutil.cpp

[discover] fix discover crush
Log: [discover] fix discover crush

fix: [discover] fix discover crush

---

src/apps/launcher/main.cpp
src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileserver.cpp
src/lib/common/manager/sessionworker.cpp
src/lib/data-transfer/core/net/networkutil.cpp

The HTTP request will be blocked if without rest, sleep 1ms for release something.
Log: Fix file transfer cannot be continuous.

fix: Fix file transfer cannot be continuous

---

src/lib/common/manager/sessionproto.h
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/common/session/protoserver.cpp
src/lib/common/session/protoserver.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/data-transfer/core/net/networkutil.cpp

Fix the login with plain text and incorrect mask issue, and fix no cancel for share.
Log: Fix login issue.

fix: Fix login issue

---

src/lib/common/manager/sessionmanager.cpp
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h

If first connect and call RPC, the RPC call will be block if the network has not connected yet.
Log: Fix RPC call block issue.

fix: Fix RPC call block issue

---

src/lib/data-transfer/core/gui/getbackup/zipworker.cpp
src/lib/data-transfer/core/gui/mainwindow_p.h
src/lib/data-transfer/core/gui/select/appselectwidget.cpp
src/lib/data-transfer/core/gui/win/drapwindowsdata.h
src/lib/data-transfer/core/gui/win/mainwindow_p_win.cpp
src/lib/data-transfer/core/net/helper/transferhepler.cpp
src/lib/data-transfer/core/net/networkutil.cpp
src/lib/data-transfer/core/net/networkutil.h

[datatransfer] add disconnect logic
Log: [datatransfer] add disconnect logic

fix: [datatransfer] add disconnect logic

---

src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileclient.h
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/webbinder.cpp
src/lib/common/manager/transferworker.cpp
src/lib/common/manager/transferworker.h

Detail info for transfer notification, and fix future exception if many files.
Log: Miss the tansfer file path after end.

fix: Miss the tansfer file path after end

---

3rdparty/CppServer/modules/CppLogging/source/logging/appenders/file_appender.cpp
3rdparty/CppServer/modules/CppLogging/source/logging/appenders/rolling_file_appender.cpp
src/common/logger.cpp

The log output into file are not be appended.
Log: Fix not append log file.

fix: Fix not append log file

---

3rdparty/CppServer/modules/CppLogging/source/logging/appenders/console_appender.cpp
src/lib/data-transfer/core/gui/transfer/transferringwidget.cpp
src/lib/data-transfer/core/net/helper/transferhepler.cpp
src/lib/data-transfer/core/net/networkutil.cpp
src/lib/data-transfer/core/net/networkutill_p.h
src/lib/data-transfer/core/utils/settinghepler.cpp
src/lib/data-transfer/core/utils/transferutil.cpp
src/lib/data-transfer/core/utils/transferutil.h

fix transsfer tip
Log: fix transsfer tip

fix: [datatransfer] fix transsfer tip

---

src/lib/common/manager/sessionmanager.cpp
src/lib/common/manager/sessionmanager.h
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/common/session/protoclient.cpp
src/lib/common/session/protoclient.h
src/lib/common/session/protoendpoint.cpp
src/lib/common/session/protoendpoint.h
src/lib/common/session/protoserver.cpp
src/lib/common/session/protoserver.h
src/lib/common/session/session.h
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/networkutill_p.h
src/lib/data-transfer/core/net/networkutil.cpp

Enable sync call for login and async call for other rpc call, 3 seconds for max timeout.
Log: Implement async rpc call.

feat: Implement async rpc call

---

src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileserver.cpp
src/lib/common/manager/sessionworker.cpp

1,The rpc response not return immediately. 2.It parse wrong file name if it contains special symbols, i.e. '&', use base64 encode it.
Log: Fix web download issue.

fix: Fix web download issue

---

src/common/commonutils.cpp
src/common/log.h
src/common/logger.cpp
src/common/logger.h
src/lib/common/httpweb/tokencache.cpp
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/transferworker.cpp
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/networkutil.cpp

The logger only output when destruct which cause slowing, separate some logs into debug version.
Log: Fix slow logout.

fix: Fix slow logout

---

3rdparty/CppServer/source/server/ws/ws.cpp

Fix build error on i386.
Log: Fix i386 build.

fix: [build] Fix i386 build

---

modules/QtZeroConf.cmake
modules/quazip.cmake

Copy the depending libs from its output dir.
Log: Fix miss depending libs.

fix: [build]Fix miss depending libs

---

src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/utils/cooperationutil.cpp

fix cooperationfailed without screen
Log: fix cooperationfailed

fix: [cooperation] fix cooperationfailed

---

src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/discover/discovercontroller.h
src/lib/cooperation/core/discover/discovercontroller_p.h
src/lib/cooperation/core/global_defines.h
src/lib/cooperation/core/gui/dialogs/settingdialog.cpp
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/gui/mainwindow.h
src/lib/cooperation/core/gui/win/mainwindow_p_win.cpp
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/utils/cooperationutil.cpp
src/lib/cooperation/core/utils/cooperationutil.h
src/lib/cooperation/core/utils/cooperationutil_p.h
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

restart zeroconf when discover deamon start
Log: fix start withour discover service
Bug: https://pms.uniontech.com/bug-view-260351.html

fix: [discover] fix start without discover service

---

.github/workflows/windows-mingw.yml
3rdparty/CMakeLists.txt
src/plugins/cooperation/core/CMakeLists.txt

[build] fix build
Log: [build] fix build
Task: https://pms.uniontech.com/task-view-354339.html

fix: [build] fix build

---

debian/changelog
src/apps/data-transfer/res/win/main.vbs
src/apps/dde-cooperation/res/win/main.vbs

new tag v0.8.5
Log: v0.8.5 override other incompatible version.

chore: [tag]v0.8.5

---

src/apps/dde-cooperation/main.cpp
src/plugins/cooperation/core/gui/widgets/deviceitem.cpp

fix Multi user startup test
Log: fix Multi user startup test
Bug: https://pms.uniontech.com/bug-view-256723.html

fix: [Multi user startup]fix Multi user startup test

---

src/dde-cooperation-translate.sh
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_bo.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

add tip translation
Log: add tip translation
Bug: https://pms.uniontech.com/bug-view-260533.html

fix: [translation] add tip translation

---

3rdparty/CppServer/include/server/http/https_client.h
3rdparty/CppServer/source/server/http/https_client.cpp
src/configs/crypt/cert.h
src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileclient.h
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/fileserver.h
src/lib/common/manager/secureconfig.cpp
src/lib/common/manager/secureconfig.h
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/transferworker.cpp
src/lib/common/session/protoclient.cpp
src/lib/common/session/protoclient.h
src/lib/common/session/protoendpoint.h
src/lib/common/session/protoserver.cpp
src/lib/common/session/protoserver.h
src/lib/common/session/session.h
src/lib/cooperation/core/net/helper/sharehelper.h

Enable ssl secure socket for rpc and https web, change proto to final.
Log: enable ssl socket.

feat: [ssl] enable ssl socket

---

src/apps/dde-cooperation/res/win/main.vbs

fix win discover error temp
Log: fix win discover error temp
Bug: https://pms.uniontech.com/bug-view-261983.html

fix: [discover] fix win discover error temp

---

debian/changelog

new tag v0.8.6
Log: new tag v0.8.6

chore: [tag]v0.8.6

---

debian/control
translations/dde-cooperation/dde-cooperation_bo.ts
translations/dde-cooperation/dde-cooperation_ug.ts

[translation] add bo ug translation
Log: [translation] add bo ug translation

fix: [translation] add bo ug translation

---

3rdparty/QtZeroConf/example/android/src/QZeroConfNsdManager.java
src/plugins/cooperation/core/gui/linux/mainwindow_p_linux.cpp

Fix title icon issue which caused by DTK updated.
Log: Fix title icon issue.
Bug: https://pms.uniontech.com/bug-view-264627.html

fix: [ui]Fix title icon issue

---

debian/changelog

v0.8.7 release.
Log: v0.8.7 release.

chore: [tag]v0.8.7

---

src/lib/cooperation/core/discover/discovercontroller.cpp
src/lib/cooperation/core/discover/discovercontroller.h
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/gui/mainwindow.h
src/lib/cooperation/core/gui/widgets/workspacewidget.cpp
src/lib/cooperation/core/gui/win/cooperationsearchedit.cpp
src/lib/cooperation/core/net/compatwrapper.cpp
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/transferwrapper.cpp
src/lib/cooperation/core/utils/historymanager.cpp
src/lib/cooperation/transfer/helper/transferhelper.cpp
src/lib/cooperation/transfer/transferplugin.cpp

Fix some search related issues, only action after press enter.
Log: Fix search related issue.

fix: Fix search related issue

---

3rdparty/coost/CMakeLists.txt
modules/compat.cmake
src/common/constant.h
src/compat/plugins/daemon/core/service/share/sharecooperationservice.cpp
src/lib/common/httpweb/fileclient.cpp
src/lib/common/manager/sessionmanager.cpp
src/lib/common/manager/sessionmanager.h
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/common/manager/transferworker.cpp
src/lib/common/manager/transferworker.h
src/lib/common/session/protoclient.cpp
src/lib/common/session/protoclient.h
src/lib/common/session/protoendpoint.h
src/lib/common/session/protoserver.cpp
src/lib/common/session/protoserver.h
src/lib/common/session/session.h
src/lib/cooperation/core/net/cooconstrants.h
src/lib/cooperation/core/net/helper/sharehelper.cpp
src/lib/cooperation/core/net/helper/sharehelper.h
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/data-transfer/core/net/networkutil.cpp
src/lib/data-transfer/core/net/protoconstants.h

Implement network heartbeat and fix some related issues.
Log: Implement network heartbeat.

fix: Implement network heartbeat

---

src/data-transfer-translate.sh
src/dde-cooperation-translate.sh
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_bo.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

[translation] add translation
Log: [translation] add translation

fix: [translation] add translation

---

src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileclient.h
src/singleton/singleapplication.cpp

The local socket file was create in user runtime and tmp, check them when App enter.
Log:Fix multi user launch issue.

fix: Single application for multi-user

---

src/apps/data-transfer/main.cpp
src/apps/dde-cooperation/main.cpp
src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileserver.cpp
src/lib/common/manager/sessionmanager.cpp
src/lib/common/manager/sessionmanager.h
src/lib/common/manager/sessionworker.cpp
src/lib/common/manager/sessionworker.h
src/lib/common/manager/transferworker.cpp
src/lib/common/manager/transferworker.h
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/share/sharecooperationservice.cpp

Notify remote cancel transfer if there is any exception, and show UI via reason.
Log:Fix exception while transfer.

fix:Fix exception for transfer

---

src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileclient.h
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/fileserver.h
src/lib/common/httpweb/webbinder.cpp
src/lib/common/httpweb/webbinder.h
src/lib/common/manager/sessionmanager.cpp
src/lib/common/manager/transferworker.cpp
src/lib/common/session/protoclient.cpp
src/lib/common/session/protoclient.h
src/lib/common/session/protoserver.cpp
src/lib/common/session/protoserver.h
src/lib/cooperation/core/net/helper/transferhelper.cpp
src/lib/cooperation/core/net/helper/transferhelper.h
src/lib/cooperation/core/net/helper/transferhelper_p.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/data-transfer/core/net/networkutil.cpp

The transfer cancel; file client unstable if cancel.
Log: Fix some known issues.

fix: Fix known issue

---

3rdparty/CuteIPC/src/CuteIPCService.cpp
modules/compat.cmake
src/common/commonutils.cpp
src/compat/apps/daemon/main.cpp
src/compat/common/commonutils.cpp
src/compat/plugins/daemon/core/daemoncoreplugin.cpp
src/compat/plugins/daemon/core/service/ipc/handleipcservice.cpp
src/compat/plugins/daemon/core/service/ipc/sendipcservice.cpp
src/compat/plugins/daemon/core/service/rpc/sendrpcservice.cpp
src/compat/plugins/daemon/core/service/servicemanager.cpp
src/compat/plugins/daemon/core/service/servicemanager.h

The cute ipc did not close local socket and the backend daemon can not exit normally.
Log: Fix the backend exit issue.

fix: Fix the backend exit issue

---

3rdparty/coost/include/co/co/thread.h
3rdparty/coost/src/co/co.cc
3rdparty/coost/src/co/sched.cc
3rdparty/coost/src/co/sched.h
3rdparty/coost/src/log/log.cc
clean_build.bat
src/lib/cooperation/core/cooperationcoreplugin.cpp

Fix dll export prob and hang at exit on windows.
Log: Fix hang at exit on windows.

fix: Fix hang at exit on windows

---

debian/changelog

new tag v0.9.0，Added a new communication method that is compatible with previous versions
Log: v0.9.0 release.

chore: [tag]v0.9.0

---

src/common/commonutils.cpp
src/plugins/cooperation/core/maincontroller/maincontroller.cpp

Fix List Status and move the log location to/etc
Log: Fix List Status and move the log location to/et
Task: https://pms.uniontech.com/task-view-357177.html

fix: [ui] Fix List Status

---

debian/changelog

v0.8.8 release.
Log: v0.8.8 release.

chore: [tag]v0.8.8

---

src/common/commonutils.cpp

Modify the storage location of log level files
Log: Modify the storage location of log level files
Task: https://pms.uniontech.com/story-view-36529.html

fix: [log] Modify the storage location of log level files

---

src/plugins/cooperation/core/gui/dialogs/settingdialog.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_bo.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

Fix translation and UI issues
Log: Fix translation and UI issues
Bug: https://pms.uniontech.com/bug-view-250549.html

fix: [trans] Fix translation and UI issues

---

debian/changelog

v0.8.9 release.
Log: v0.8.9 release.

chore: [tag]v0.8.9

---

debian/changelog

v0.9.1 release.
Log: v0.9.1 release.

chore: [tag] v0.9.1 release

---

src/lib/cooperation/core/CMakeLists.txt
src/lib/cooperation/core/discover/deviceinfo.cpp
src/lib/cooperation/core/discover/deviceinfo.h
src/lib/cooperation/core/discover/deviceinfo_p.h
src/lib/cooperation/core/global_defines.h
src/lib/cooperation/core/gui/linux/mainwindow_p_linux.cpp
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/gui/mainwindow.h
src/lib/cooperation/core/gui/mainwindow_p.h
src/lib/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/lib/cooperation/core/gui/widgets/cooperationstatewidget.h
src/lib/cooperation/core/gui/widgets/deviceitem.cpp
src/lib/cooperation/core/gui/widgets/devicelistwidget.cpp
src/lib/cooperation/core/gui/widgets/mobilewidget.cpp
src/lib/cooperation/core/gui/widgets/mobilewidget.h
src/lib/cooperation/core/gui/widgets/workspacewidget.cpp
src/lib/cooperation/core/gui/widgets/workspacewidget.h
src/lib/cooperation/core/gui/widgets/workspacewidget_p.h
src/lib/cooperation/transfer/CMakeLists.txt

add mobile ui
Log: add mobile ui
Task: https://pms.uniontech.com/story-view-35783.html

fix: [mobile] add mobile ui

---

3rdparty/CppServer/modules/CppCommon/include/filesystem/path.h
3rdparty/CppServer/modules/CppCommon/source/filesystem/path.cpp
android/app/src/main/java/com/deepin/assistant/ui/activity/HomeActivity.kt
android/app/src/main/res/layout/home_fragment.xml
android/app/src/main/res/values-zh/strings.xml
android/app/src/main/res/values/strings.xml
android/library/droidvnc-ng/src/main/java/net/christianbeier/droidvnc_ng/Defaults.kt
android/library/droidvnc-ng/src/main/java/net/christianbeier/droidvnc_ng/InputService.java
android/library/droidvnc-ng/src/main/java/net/christianbeier/droidvnc_ng/MainService.java
android/modules/cooperation/src/main/cpp/sessionhelper.cpp
src/lib/cooperation/CMakeLists.txt
src/lib/cooperation/core/CMakeLists.txt
src/lib/cooperation/core/cooperationcoreplugin.cpp
src/lib/cooperation/core/gui/phone/qt2keysum.h
src/lib/cooperation/core/gui/phone/screenmirroringwindow.cpp
src/lib/cooperation/core/gui/phone/screenmirroringwindow.h
src/lib/cooperation/core/gui/phone/vncviewer.cpp
src/lib/cooperation/core/gui/phone/vncviewer.h
src/lib/cooperation/core/net/cooconstrants.h
src/lib/cooperation/core/net/helper/phonehelper.cpp
src/lib/cooperation/core/net/helper/phonehelper.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/transfer/CMakeLists.txt

Add projection view which integrated the vncclient.
Log: Add projection UI.

feat: [cast]Add projection UI

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/deepin/assistant/ui/activity/HomeActivity.kt
android/app/src/main/java/com/deepin/assistant/ui/fragment/FirstFragment.kt
android/app/src/main/java/com/deepin/assistant/ui/fragment/HomeFragment.kt
android/app/src/main/java/com/deepin/assistant/ui/scan/ScanActivity.kt
android/app/src/main/java/com/deepin/assistant/ui/scan/ScanView.kt
android/app/src/main/res/drawable/back_ic.xml
android/app/src/main/res/layout/activity_scan.xml
android/app/src/main/res/layout/first_fragment.xml
android/app/src/main/res/layout/home_fragment.xml
android/app/src/main/res/values-zh/strings.xml
android/app/src/main/res/values/strings.xml
android/modules/cooperation/src/main/cpp/cooperation.cpp
android/modules/cooperation/src/main/cpp/sessionhelper.cpp
android/modules/cooperation/src/main/cpp/sessionhelper.h
android/modules/cooperation/src/main/java/com/deepin/cooperation/JniCooperation.kt
src/lib/cooperation/core/net/compatwrapper.cpp
src/lib/cooperation/core/net/cooconstrants.h
src/lib/cooperation/core/net/helper/phonehelper.cpp
src/lib/cooperation/core/net/helper/phonehelper.h
src/lib/cooperation/core/net/networkutil.cpp
src/lib/cooperation/core/net/networkutil.h

Replace scanned QR codes and correct some UI logic
Log: Add some interaction logic
Task: https://pms.uniontech.com/story-view-35783.html

feat: [android] Add some interaction logic

---

android/app/src/main/java/com/deepin/assistant/ui/activity/HomeActivity.kt
android/library/droidvnc-ng/src/main/java/net/christianbeier/droidvnc_ng/Defaults.kt
src/lib/cooperation/core/gui/phone/screenmirroringwindow.cpp
src/lib/cooperation/core/gui/phone/vncviewer.cpp
src/lib/cooperation/core/gui/phone/vncviewer.h

Resize vnc view after mobile screen rotate, fix some known issues.
Log: Enable screen view rotation.

fix: [vncview]Enable screen view rotation

---

android/app/src/main/java/com/deepin/assistant/services/InputService.kt
android/app/src/main/java/com/deepin/assistant/services/MediaProjectionService.kt

Fix build is broken by format issue and correct app name as input service.
Log: Fix build issue.

fix: Fix build issue

---

src/lib/cooperation/libvnc.cmake

It miss the generated rfbconfig.h header file.
Log: Fix build issue.

fix: [build]Fix build issue

---

src/lib/cooperation/core/gui/phone/screenmirroringwindow.cpp
src/lib/cooperation/core/gui/phone/screenmirroringwindow.h
src/lib/cooperation/core/gui/phone/vncrecvthread.h
src/lib/cooperation/core/gui/phone/vncviewer.cpp
src/lib/cooperation/core/gui/phone/vncviewer.h
src/lib/cooperation/core/net/helper/phonehelper.cpp

The vnc view's height do not match the scale height, that cause rotation again and again.
Log: Fix screen rotation issue

fix: Fix screen rotation issue

---

src/lib/cooperation/core/gui/phone/screenmirroringwindow.cpp

Remove the bottom style setting which will disable DIconButton style.
Log: Fix action button press style.

fix: Fix action button press style

---

src/lib/cooperation/core/net/helper/phonehelper.cpp
src/lib/cooperation/core/net/helper/phonehelper.h

Fix crashes and multiple pop ups
Log: Fix crashes and multiple pop ups
Bug: no

fix: [dailog] Fix crashes and multiple pop ups

---

src/lib/cooperation/core/gui/dialogs/settingdialog.cpp
src/lib/cooperation/core/gui/widgets/cooperationstatewidget.cpp
src/lib/cooperation/core/gui/widgets/firsttipwidget.cpp
src/lib/cooperation/core/gui/widgets/firsttipwidget.h

Fix some UI layout issueif mode or font size changed.
Log: Fix some ui layout issues.
Bug: https://pms.uniontech.com/bug-view-280049.html
https://pms.uniontech.com/bug-view-280071.html
https://pms.uniontech.com/bug-view-280075.html

fix: [ui]Fix some ui layout issues

---

android/app/build.gradle
android/app/src/main/java/com/deepin/assistant/ui/activity/HomeActivity.kt
src/lib/cooperation/core/net/helper/phonehelper.cpp

Set the product url into QR code, and parse it by new way.
Log: Update QR with url.

feat: [cast]Update QR with url

---

debian/changelog

New tag v1.0.3.
Log: v1.0.3 release.

chore: [tag]v1.0.3 release

---

src/apps/dde-cooperation-transfer/main.cpp
src/apps/dde-cooperation/main.cpp
src/lib/cooperation/core/CMakeLists.txt
src/lib/cooperation/core/cooperationcoreplugin.cpp
src/lib/cooperation/transfer/CMakeLists.txt
src/lib/cooperation/transfer/helper/transferhelper.cpp
src/lib/cooperation/transfer/helper/transferhelper.h
src/singleton/singleapplication.cpp

Clear the file delivery and its depending backend relationship by ipc socket, and fix the single application show if it is hidden.
Log: Fix file delivery and single app show issue.
Bug: https://pms.uniontech.com/bug-view-290857.html

fix: Fix file delivery and single app show issue

---

src/plugins/cooperation/core/cooperationcoreplugin.cpp
src/plugins/cooperation/core/gui/mainwindow.cpp
src/plugins/cooperation/core/gui/widgets/devicelistwidget.cpp

fix: [ui] Unable to open from launcher after closing
Unable to open from launcher after closing
Log: fix some ui bug
Bug: https://pms.uniontech.com/bug-view-282501.html

fix: [ui] Unable to open from launcher after closing

---

debian/changelog

New tag v1.0.4
Log: v1.0.4 release.

chore: [tag]v1.0.4 release

---

src/lib/cooperation/core/gui/linux/mainwindow_p_linux.cpp
src/lib/cooperation/core/gui/mainwindow.cpp
src/lib/cooperation/core/gui/phone/phonewidget.cpp
translations/dde-cooperation/dde-cooperation.ts
translations/dde-cooperation/dde-cooperation_bo.ts
translations/dde-cooperation/dde-cooperation_ug.ts
translations/dde-cooperation/dde-cooperation_zh_CN.ts
translations/dde-cooperation/dde-cooperation_zh_HK.ts
translations/dde-cooperation/dde-cooperation_zh_TW.ts

Add the download link into Qrcode page and merge menus.
Log: Add download link.
Task: https://pms.uniontech.com/story-view-37685.html

feat: Add download link

---

debian/control
src/lib/cooperation/core/CMakeLists.txt

Change the dde-cooperation depends the transfer package in order to integrate it into OS. And fix a build issue for win.
Log: change package's depend.

chore: Change depending

---

.github/workflows/windows-msvc.yml
clean_build.bat
cmake/version.cmake

Change the github action for msvc build.
Log: Change msvc action.

chore: [ci]Change msvc action

---

src/lib/data-transfer/core/utils/settinghepler.cpp

Change the DBus interfaces for V25.
Log: Adapt DBus interface

fix: Adapt DBus interface

---

debian/changelog

New tag v1.0.5
Log: v1.0.5 release.

chore: [tag]v1.0.5 release

---

3rdparty/CppServer/modules/CppCommon/source/time/timestamp.cpp
debian/source/format

source/format 类型错误 riscv64架构构建错误
Log:

fix: source/format 类型错误 riscv64架构构建错误

---

3rdparty/CppServer/source/server/asio/ssl_client.cpp
src/lib/common/httpweb/fileclient.cpp
src/lib/common/httpweb/fileclient.h
src/lib/common/httpweb/fileserver.cpp
src/lib/common/httpweb/fileserver.h
src/lib/common/httpweb/syncstatus.h
src/lib/common/manager/sessionmanager.cpp
src/lib/common/manager/sessionmanager.h
src/lib/common/manager/transferworker.cpp
src/lib/common/manager/transferworker.h

It disconnected with server afer every file download, cause create new SSL context which cause mem leak. It should use the same http client to download all files and free transfer worker after finished.
Log: Fix memory leak for transfer.

fix: Fix memory leak

---

.github/workflows/windows-msvc.yml
clean_build.bat
src/apps/CMakeLists.txt
src/apps/data-transfer/main.cpp
src/lib/common/manager/filesizecounter.cpp
src/lib/common/manager/filesizecounter.h
src/lib/common/manager/sessionmanager.cpp
src/lib/data-transfer/core/CMakeLists.txt
src/lib/data-transfer/core/datatransfercoreplugin.cpp
src/lib/data-transfer/core/net/helper/transferhepler.cpp
src/lib/data-transfer/core/net/networkutil.cpp
src/lib/data-transfer/core/utils/settinghepler.cpp

1. Remove the backend daemon for data transfer.
2. Fix some resource did not release correctly.

Remove the backend daemon for data transfer

---

debian/changelog

New tag v1.0.6
Log: v1.0.6 release.

chore: [tag]v1.0.6 release

---

src/configs/json/org_deepin_dde_cooperation.hpp

Add DDE cooperation config class.
Log: add cooperation config interface

chore: add cooperation config interface

---

debian/changelog

v1.0.8 release.
Log: v1.0.8 release.

chore: [tag] New tag v1.0.8

---

debian/changelog

v1.0.10 release.
Log: v1.0.10 release.

chore: [tag] New tag v1.0.10

---

debian/changelog

v1.0.11 release.
Log: New tag v1.0.11.

chore: [tag] New tag v1.0.11
